src/c++/libos/posix/posix_queue.cc

In `posix_queue.cc`, define `alloc_latency` only when the `DMTR_PROFILE` macro is set (otherwise, profiling-related type and variables are undefined).

Put profiling initialization behind DMTR_PROFILE macro

---

src/c++/libos/lwip/lwip_queue.cc

Fixes issue where right now, for the DPDK lwip stack, the entire SGA won't be freed properly (only the last segment).

Fix bug relating to freeing sga buf for lwip

---

src/rust/catnip_libos/CMakeLists.txt

In this Pull Request, I fix the bad target name for LibOS Catnip.

Bad CMake Target for LibOS Catnip

---

src/catnip-libos/src/lib.rs

Description
========
In this Pull Request I patched the `dmtr_init()` function so that device parameters can be override by environment variables.

[catnip-libos] Read Dev Param from Env

---

README.md

Description
========
Fix typo in run instructions on README.

[doc] Fix Typo on Run Instructions

---

Cargo.toml
src/catnap/mod.rs
src/catnap/runtime.rs
src/catnip/runtime/memory/manager.rs
src/catnip/runtime/memory/mod.rs
src/catpowder/runtime/memory.rs
src/demikernel/libos.rs
src/lib.rs

Description
========
In this commit I update the `runtime` crate so as to match the latest `dev` release in https://github.com/demikernel/runtime. As well, I've patched both mainline and test code accordingly.
Overall, this bumps scatter-gather allocation/free to fail instead of panicking.
Related Issues
===========
- https://github.com/demikernel/runtime/issues/12

[contrib] Updating Contrib

---

src/catnap/futures/mod.rs
src/catnap/mod.rs

Description
========
In this Pull Request, I fixed issue https://github.com/demikernel/demikernel/issues/54.

[demikernel] Uniform `OperationResult` Across LibOSes

---

Cargo.toml
src/catnap/mod.rs
src/demikernel/libos.rs

Description
========
In this PR I fix the following issues:
- https://github.com/demikernel/demikernel/issues/64
- https://github.com/demikernel/demikernel/issues/67

[catnap] Implementing Missing System Calls

---

Makefile
src/catnip/runtime/memory/manager.rs
tests/sga.rs

Description
========
This PR fixes issue https://github.com/demikernel/demikernel/issues/51.
In summary, the pointer arithmetic used for releasing allocated `mbufs` is bad. Instead of relying on this technique, I simply changed current code to use the returned `mbuf` pointer.
Since the management of DPDK buffers is not well design, I've also placed a warning, so that we know when we are relying on this allocation strategy.
Finally, I introduce unit-tests that ensure that the current logic works as expected.
This component will be strongly re-architected in a next PR.

[catnip] Bad Scatter-Gather Allocation/Free

---

.github/workflows/catnap-unit-tests.yml
.github/workflows/catnip-unit-test.yml
.github/workflows/catpowder-unit-test.yml
src/catnip/runtime/memory/config.rs
src/catnip/runtime/memory/consts.rs
src/catnip/runtime/memory/manager.rs
src/catnip/runtime/memory/mbuf.rs
src/catnip/runtime/memory/mempool.rs
src/catnip/runtime/memory/mod.rs
src/catnip/runtime/network.rs
tests/pushpop.rs
tests/sga.rs

Description
========
In this PR, I mostly introduce the enhancement that is described in https://github.com/demikernel/demikernel/issues/83. 
Here is a digest of the commits:
- In commit 2a31472a5c8bcd6fb8af00cc75be92f6d69ae14a I drop bad checks that were used in the pointer arithmetic for allocating/releasing `mbufs`.
- In commit dc73ffee6c1d4c56d8780a5e4eff2b56c9d0fbc5 I introduce the `MemoryPool` abstraction.
- In commit c31d48bb67b2039986c1790d0012d9c9d785ecd9 and 729f0915277ae2e27082cf763ad1c419e76f1fd2 I refactor the code to rely on the `MemoryPool` abstraction
- In commit 837ed5049129f8678ef2e8a6005e85c5936a8534 I drop the indirect memory pool, because it is not required to provide the shallow copy of `mbufs` ([`rte_pktmbuf_clone`](https://elixir.bootlin.com/dpdk/latest/source/lib/m …

[catnip] Memory Pool Abstraction

---

src/demikernel/bindings.rs

Description
========
In this PR I fix issue https://github.com/demikernel/demikernel/issues/94.
Additionally, note also that I added dummy calls for the `setsockopt()` and `getsockopt()` system calls that shall be introduced in upcoming versions of Demikernel.
Related Issues
==========
- https://github.com/demikernel/demikernel/issues/72
- https://github.com/demikernel/demikernel/issues/73
- https://github.com/demikernel/demikernel/issues/74

[pdpix] Don't Panic on System Calls

---

src/catnap/futures/mod.rs
src/catnap/futures/pop.rs
src/catnap/futures/push.rs
src/catnap/futures/pushto.rs
src/catnap/mod.rs
src/catnap/runtime.rs
src/catnip/runtime/memory/dpdkbuf.rs
src/catnip/runtime/memory/manager.rs
src/catpowder/mod.rs
src/catpowder/runtime/memory.rs
src/catpowder/runtime/network.rs
src/demikernel/dbuf.rs
src/demikernel/libos.rs
src/demikernel/mod.rs
tests/common/catnap.rs
tests/common/catpowder.rs
tests/pushpop.rs

Description
========
In this PR I fix issue https://github.com/demikernel/demikernel/issues/86.
Here is a digest of the commits:
- In commit aab28885ea2fad42ded151b3bef0a461c3ee7695 I introduce the new `HeapBuffer` abstraction.
- In commits ee0efe081b96594e29036ced6b4ccb0457964d7e, 1b024fbaf5f8a441eacd327f22bdb1b2329170ab,  I patch our LibOSes to rely on this new abstraction.
Also, note that:
- In commit 1c027eb81b24315f83a56ff27713cc2a33f130d8 I fix a bug in our TCP push pop test. It was expecting a packet of a given content and size. This check was not good because this unit tests performns a one-directrion transmission.

[memory] Introduce a Better Abstraction for Runtime Buffers

---

.github/workflows/catnap-build.yml
.github/workflows/catnap-tcp-pingpong.yml
.github/workflows/catnap-tcp-pushpop.yml
.github/workflows/catnap-udp-pingpong.yml
.github/workflows/catnap-udp-pushpop.yml
.github/workflows/catnap-unit-tests.yml
.github/workflows/catnip-build.yml
.github/workflows/catnip-tcp-pingpong.yml
.github/workflows/catnip-tcp-pushpop.yml
.github/workflows/catnip-udp-pingpong.yml
.github/workflows/catnip-udp-pushpop.yml
.github/workflows/catnip-unit-test.yml
.github/workflows/catpowder-build.yml
.github/workflows/catpowder-tcp-pingpong.yml
.github/workflows/catpowder-tcp-pushpop.yml
.github/workflows/catpowder-udp-pingpong.yml
.github/workflows/catpowder-udp-pushpop.yml
.github/workflows/catpowder-unit-test.yml

Description
========
In this PR I drop workflow dispatch in GitHub actions, because branch filtering is no longer supported on this dispatching option.

[test] Drop Workflow Dispatch

---

src/demikernel/bindings.rs

Description
========
This PR fixes  #116

[pdpix] Missing Argument Check in `wait_any()`

---

Makefile
README.md

Description
-------------
This PR addresses issue https://github.com/demikernel/demikernel/issues/45.
It introduces changes in the build system to copy build artifacts to a user-supplied installation location.

[build] Copy Build Artifacts to a Installation Location

---

Cargo.toml
src/catcollar/futures/connect.rs
src/catcollar/iouring.rs
src/catcollar/mod.rs
src/catcollar/runtime/mod.rs
src/catnap/futures/connect.rs
src/catnap/futures/pushto.rs
src/catnap/mod.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/122.
Digest of Changes
---------------------
- Bumped `nix` crate to `v0.24.0`
- Dropped deprecated `Sockaddr` in Catnap
- Dropped deprecated `Sockaddr` in Catcollar

[contrib] Upgrade `nix` to `v0.24.0` Catnap and Catcollar

---

include/demi/libos.h
src/catcollar/mod.rs
tests/c/Makefile
tests/c/syscalls.c
tests/c/udp-push-pop.c

Description
-------------
This PR is a partial fix for issue https://github.com/demikernel/demikernel/issues/131.
Summary Changes
----------------------
- Fixed signature of `demi_init()` to be compliant with POSIX.
- Introduced `udp-push-pop` test for C API.
Further Considerations
--------------------------
- The newly introduced test `udp-push-pop` has not yet been integrated with our regression system.

[test] UDP Push Pop Test for C API

---

src/rust/demikernel/bindings.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/144.
- Renamed `sockaddr_to_ipv4endpoint()` to `test_sockaddr_to_socketaddrv4()`
- Dropped useless byte ordering conversion for socket address in `test_sockaddr_to_socketaddrv4`.
- Introduced a test unit for bug https://github.com/demikernel/demikernel/issues/144.
- Fixed missing edianness conversion for port number in `test_sockaddr_to_socketaddrv4()`
- Added check for `AF_INET` in `test_sockaddr_to_socketaddrv4()`

[pdpix] Missing Endianness Conversion for Port Number

---

src/rust/catnap/futures/mod.rs
src/rust/catnap/futures/pop.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/147.
Sumary of Changes
----------------------
- Changed `PopFuture::poll()` to use `recvfrom()` and return the source address of the message
- Changed the `Operation::get_result()` to set the address in `OperationResult` accordingly
Additional Information
--------------------------
- The verbose conversion in `recvfrom()` is required because `nix` does not provide a conversion function between `SockaddrStorage` and `SocketAddrV4` (https://docs.rs/nix/latest/nix/sys/socket/union.SockaddrStorage.html). Once we drop the use of `nix` in favor of `libc` we should get rid of this.
- There is a similar issue with Catcollar, but it is harder to fix. See https://github.com/demikernel/demikernel/issues/148 for …

[catnap] Set Source Address in `OperationResult` for `pop()`

---

tests/c/Makefile
tests/c/tcp-ping-pong.c
tests/c/udp-ping-pong.c
tests/c/udp-push-pop.c

Description
-------------
This PR is a partial fix for https://github.com/demikernel/demikernel/issues/131.
- Introduced C test for TCP ping pong

[test] TCP Ping Pong for C API

---

src/rust/catcollar/mod.rs
src/rust/catnap/mod.rs
src/rust/demikernel/config.rs
src/rust/lib.rs

Partially addresses this issue: https://github.com/demikernel/inetstack/issues/124
This is a part of a multi-part series of PRs. This series aims to move from custom types that support network-related data structures to standard library types in Rust. Multiple other PRs will follow targetting similar changes to other libraries (e.g. inetstack, runtime).

[network] Move to std network types

---

Cargo.toml
src/rust/catcollar/futures/mod.rs
src/rust/catcollar/futures/pop.rs
src/rust/catcollar/futures/push.rs
src/rust/catcollar/futures/pushto.rs
src/rust/catcollar/iouring.rs
src/rust/catcollar/runtime/mod.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/148.
- Changed `IoUring` to rely on `io_uring_prep_recvmsg()` and thus be able to get the socket address of the source.
- Changed lookip logic in `IoUring` to use the `msghdr` rather than the buffer address
- Changed futures accordinly

[catcollar] Set Source Address in `OperationResult` for `pop()`

---

include/demi/wait.h
man/demi_wait.md
src/rust/catcollar/mod.rs
src/rust/catnap/mod.rs
src/rust/catnip/mod.rs
src/rust/catpowder/mod.rs
src/rust/demikernel/bindings.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network.rs
src/rust/inetstack/mod.rs
tests/c/Makefile
tests/c/linux.mk
tests/c/syscalls.c

Description
-------------
This PR partially fixes https://github.com/demikernel/demikernel/issues/61.
- Added `timedwait()` system call to PDPIX
- Added implementation of `timedwait()` for Catnap, Catnip, Catpowder and Catcollar LibOses
- Added manual pages for `timedwait()`
- Added invalided system call unit test for `timedwait()`

[pdpix] `timedwait()` System Call

---

src/rust/catcollar/futures/accept.rs
src/rust/catcollar/mod.rs
src/rust/catnap/futures/accept.rs
src/rust/catnap/mod.rs
src/rust/lib.rs
src/rust/pal/linux.rs
src/rust/pal/mod.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/281 and https://github.com/demikernel/demikernel/issues/282.
- Introduced a PAL (Platform Abstraction Play) module for placing platform-specific code.
- Fixed Catnap to set `SO_REUSEPORT` when creating sockets.
- Fixed Catcollar to set `SO_REUSEPORT` when creating sockets.

[catnap][catcollar] `demi_socket()` Fails with `EADDRINUSE`

---

src/rust/catnip/runtime/memory/manager.rs
src/rust/runtime/memory/buffer/dpdkbuffer.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/299.
- Changed `DPDKBuffer::adjust()` to dump arguments that cause a panic
- Changed `DPDKBuffer::trim()` to dump arguments that cause a panic.
- Removed call to `DPDKBuffer:trim()` when cloning scatter-gather arrays.

[catnip] Bug Fix: Don't Trim on SGA Clone

---

src/rust/catcollar/runtime/memory.rs
src/rust/catnap/runtime.rs
src/rust/catnip/runtime/memory/manager.rs
src/rust/catpowder/runtime/memory.rs
src/rust/lib.rs
src/rust/runtime/memory/buffer/databuffer.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/301.
- Renamed the `DataBuffer::into_raw()` to `DataBuffer::into_raw_parts()`.
- Changed `DataBuffer::into_raw_parts()` to return a pair of pointers (one for the start of the buffer and one for the start of the data)
- Changed scatter-gather management in LibOSes accordingly.

[pdpix] Wrong Conversions Between `DataBuffer` and `demi_sgarray_t`

---

src/rust/catcollar/mod.rs
src/rust/catnap/mod.rs
src/rust/catnip/mod.rs
src/rust/catpowder/mod.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network.rs
src/rust/inetstack/mod.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/295
- Dropped `wait2()` from all LibOSes
- Dropped `wait_any2()` from all LibOSes
- Dropped `push2()` from all LibOSes
- Dropped `pushto2()` from all LibOSes

[pdpix] Drop Deprecated System Calls

---

examples/rust/tcp-dump.rs
examples/rust/tcp-echo.rs
examples/rust/tcp-ping-pong.rs
examples/rust/tcp-pktgen.rs
examples/rust/tcp-push-pop.rs
examples/rust/udp-dump.rs
examples/rust/udp-echo.rs
examples/rust/udp-ping-pong.rs
examples/rust/udp-pktgen.rs
examples/rust/udp-push-pop.rs
examples/rust/udp-relay.rs
examples/rust/windows.mk
src/rust/catcollar/mod.rs
src/rust/catnap/mod.rs
src/rust/demikernel/bindings.rs
src/rust/inetstack/mod.rs
src/rust/pal/constants.rs
src/rust/pal/data_structures.rs
src/rust/pal/functions.rs
src/rust/pal/mod.rs
src/rust/runtime/types/memory.rs
tests/rust/tcp.rs
tests/rust/udp.rs

Partially fixes issue https://github.com/demikernel/demikernel/issues/274.
More PRs will follow:
(1) Refactor the PAL to make platform/subsystem specific hierarchy in the directory structure.
(2) Tests and examples on Windows
(3) Catnap for Windows (makefiles, code, using CatnapW where applicable)

[winport] Platform Abstraction Layer for Network 

---

src/rust/lib.rs
src/rust/pal/arch.rs
src/rust/pal/mod.rs
src/rust/runtime/memory/buffer/demibuffer.rs
src/rust/runtime/memory/buffer/mod.rs

This PR introduces the `DemiBuffer` abstraction.  The intent is to replace the `Buffer` enumeration (along with its `DataBuffer` and `DpdkBuffer` subtypes) with this new abstraction.
The motivation behind this is that the existing `DataBuffer` differed greatly from `DpdkBuffer` in its capabilities, making it difficult to present a uniform `Buffer` interface.   In particular, the `DataBuffer` implementation precluded adding some desired functionality to `Buffer` that is either already present in DPDK or is easy to add to `DpdkBuffer`.  Things like splitting buffers without copying any of the data, chaining buffers together to represent a packet, and queueing buffers using internal linkage fields (to avoid allocations).
More explanation of the `DemiBuffer` type is provided in the …

[runtime] DemiBuffer Abstraction

---

src/rust/runtime/memory/buffer/demibuffer.rs

Description
-------------
This is a workaround for https://github.com/demikernel/demikernel/issues/310.
- Disabled unit tests for `DemiBuffer`.

[test] Disable `DemiBuffer` UnitTest

---

.gitignore
examples/c/linux.mk
examples/c/windows.mk
linux.mk
tests/c/windows.mk
tests/windows.mk
windows.mk

Partially addresses issue https://github.com/demikernel/demikernel/issues/274.
This PR adds the Makefiles for Windows build. Subsequent PRs will add the CatnapW LibOS for Windows and test/example builds for Windows.
**_Note that the build will NOT work on Windows just with this change. This is a part of a series of PRs to follow._**

[winport] Add Windows makefiles

---

src/rust/runtime/memory/buffer/demibuffer.rs

This PR fixes [Issue#310](https://github.com/demikernel/demikernel/issues/310).
The drop code was referencing `DemiBuffer`'s `ptr` field directly, rather than calling the internal `get_ptr()` method to get the `MetaData` pointer.
One take-away from this experience, is that we can't trust individual unit tests to (indirectly) test `drop` methods.  The DemiBuffer unit tests ran fine when run individually, or even together.  It appears to be non-deterministic as to whether Cargo's test harness keeps the test environment around long enough for destructors to run.

[runtime] Bad Deref in `DemiBuffer::drop()` Causes Segmentation Fault

---

src/rust/catcollar/mod.rs
src/rust/catnap/mod.rs
src/rust/catnip/mod.rs
src/rust/catpowder/mod.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network.rs
src/rust/inetstack/mod.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/306.
- Moved definition of `wait()` to PDPIX layer
- Moved definition of `wait_any()` to PDPIX layer
- Moved definition of `timedwait()` to PDIX layer
- Dropped definition of `wait_any()` from Catnap, Catnip, Catpowder and Catcollar
- Dropped definition of `timedwait()` from Catnap, Catnip, Catpowder and Catcollar

[pdpix] Generic `wait()`, `wait_any()` and `timedwait()`

---

src/rust/catnip/runtime/mod.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/326.
- Added a check for the return value of `rte_eal_init()`

[catnip] Missing Check for Return Value of `rte_eal_init()`

---

examples/c/tcp-ping-pong.c
examples/c/tcp-push-pop.c
examples/c/udp-ping-pong.c
examples/c/udp-push-pop.c
examples/rust/tcp-dump.rs
examples/rust/tcp-echo.rs
examples/rust/tcp-ping-pong.rs
examples/rust/tcp-pktgen.rs
examples/rust/tcp-push-pop.rs
examples/rust/udp-dump.rs
examples/rust/udp-echo.rs
examples/rust/udp-ping-pong.rs
examples/rust/udp-pktgen.rs
examples/rust/udp-push-pop.rs
examples/rust/udp-relay.rs
include/demi/wait.h
man/demi_wait.md
src/rust/demikernel/bindings.rs
src/rust/demikernel/libos/mod.rs
tests/c/syscalls.c

This PR is a fix for Issue #61.
- Added an interval timeout parameter to `demi_wait()` and `demi_wait_any()`.
- Updated all test and example code in the demikernel repo that uses these call(s) to supply the additional parameter.
- Updated the manual page.
- Changed the internal Rust `wait()` call's implementation to call `wait_any()`.
Note: I originally planned to re-implement `demi_wait()` and `demi_wait_any()` on top of `demi_timedwait()` (i.e. convert the wait interval to an absolute timeout) but had to abort that plan once I noticed in the documentation that `SystemTime` is not guaranteed to be monotonically increasing, and thus isn't suitable for interval timing.  (While the implementation of these is technically system-dependent, Rust expects `SystemTime` to be implemented using the …

[pdpix] Timeout Interval Parameter to `demi_wait()` and `demi_wait_any()`

---

src/rust/collections/shared_ring.rs

This PR marks the two flaky unit tests for `SharedRingBuffer` as `#[ignore]` until they can be fixed to not corrupt the test infrastructure.
See Issue #318.

[collections] Mark Flaky `SharedRingBuffer` Unit Tests as `#[ignore]`

---

src/rust/demikernel/bindings.rs
src/rust/demikernel/libos/mod.rs

Description
-------------
This is a partial fix for [pdpix] Use trace Logging Level to Propagate Unexpected Conditions.
- Changed logging messages on PDPIX to `trace` level.
- These do not concern the point where the unexpected situation happened.
- Renamed socket queue descriptors in PDPIX layer to `sockqd` to match the used convention in the file.
- Fixed some types in the API docs in the PDPIX layer.
- Added missing types in `wait()`.

[pdpix] Use trace Logging Level to Propagate Unexpected Conditions

---

src/rust/inetstack/collections/hashttlcache/mod.rs
src/rust/inetstack/collections/hashttlcache/tests.rs

This PR add a remove function for the hashttlcache. Due to the removed value being placed in the graveyard, we do not currently return the removed value as well because that would require us to clone it. I believe this is incorrect behavior but we're unclear on what the graveyard's functionality is or if we will use it going forward so I will just leave this fix as is for now.

[arp] Add Remove Function

---

src/rust/inetstack/mod.rs

This PR fixes Issue #194.
Basically, we have a filter at the Ethernet layer that is intended to drop packets not actually addressed to us (Ethernet MAC address).  In the past, we accepted incoming packets addressed to our actual EUI-48, and also ones sent to the broadcast address (needed for ARP).  But we dropped packets addressed to a multicast address that our NIC was listening on (after printing a warning).
This PR now allows multicast packets to be received by the Ethernet layer of our stack (they still have to pass the IP address checks of course).
Note: There used to be a [linked Issue in a different repo](https://github.com/demikernel/runtime/issues/17) (back when we had these separate) to add the `is_multicast()` functionality.  I added that in a separate PR before the repos were …

[inetstack] Accept Ethernet Multicast Packets

---

examples/rust/udp-echo.rs
src/rust/catnip/interop.rs
src/rust/pal/functions.rs

The Platform Abstraction Layer (PAL) implements the OS specific artifacts for the LibOSes. The aim is to isolate these implementation details at a single place (i.e. the PAL).
Partially addresses issue https://github.com/demikernel/demikernel/issues/274.

[catnip] Use PAL in Catnip

---

src/rust/inetstack/protocols/tcp/established/ctrlblk.rs

Description
--------------
This is a workaround for https://github.com/demikernel/demikernel/issues/369.
- Added code for push a zero-length buffer when a FIN has been received and the concerned TCP connection is closing.

[inetstack] Push Empty Buffer on FIN

---

.github/workflows/catnip.yml
Cargo.toml
scripts/config/azure.yaml
scripts/config/default.yaml
scripts/setup/dpdk.sh
src/rust/catnip/runtime/mod.rs

Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/256
- Updated `scripts/setup/dpdk.sh` to support DPDK 22.11
- Updated `dpdk-rs` and fixed concerned changes

[build] Bumping DPDK Version

---

src/rust/catnapw/futures/pop.rs
src/rust/catnapw/mod.rs
src/rust/catnapw/runtime.rs

Partially addresses issues https://github.com/demikernel/demikernel/pull/320 and https://github.com/demikernel/demikernel/issues/274 for catnapw (Windows)

[catnapw] Use `DemiBuffer` Instead of `Buffer`/`DataBuffer`

---

.github/workflows/catnapw.yml
doc/building-windows.md
windows.mk

Description
-------------
- This PR is a partial fix for https://github.com/demikernel/demikernel/issues/386.
- This PR is a partial fix for https://github.com/demikernel/demikernel/issues/388.
- Integrated Catnapw building with our regression system.
- Building is enabled on dev branch only, because the GitHub Actions plugin that we use does not support passing environment variables to a Windows remote.
- Disabled C format checking on Windows, because it is not implemented.
- Wrote a documentation with Build instructions for Windows.

[ci] Initial Integration of Catnapw with Regression System

---

linux.mk

This commit is a partial fix for https://github.com/demikernel/demikernel/issues/403
- Set `RUST_LOG=trace` on Linux, when running in debug mode.

[build] Set `RUST_LOG=trace` when Running in Debug Mode

---

src/rust/pal/linux/mod.rs

This PR fixes https://github.com/demikernel/demikernel/issues/405
- Fixed the API level for `setsockopt()` when setting `SO_REUSEPORT`.

[pal] Bad Level When Setting `SO_REUSEPORT`

---

README.md
doc/building.md
doc/testing.md

This PR closes https://github.com/demikernel/demikernel/issues/359
- Fixed outdated Ubuntu version in `README.md`.
- Fixed missing Catmem LibOS badge in `README.md`.
- Moved build instructions to a standalone document.

[doc] Moving Build Instructions to Standalone Document

---

src/rust/catcollar/mod.rs
src/rust/catnap/mod.rs
src/rust/catpowder/interop.rs
src/rust/pal/linux/mod.rs

This PR closes https://github.com/demikernel/demikernel/issues/412
- Added a helper function`sockaddrv4_to_sockaddr_in()` to perform the conversion between a `std::net::SocketAddrV4` to `libc::sockaddr_in`
- Changed the concerned code to rely on the helper function.
- Changed the conversion of `sin_port` and `sin_addr.s_addr` to be on network order.

[pal] Helper Function to Convert `std::net::SocketAddrV4` to `libc::sockaddr_in`

---

tools/demikernel-ci.py

This PR addresses #414. It adds support for creating a separate directory for each run of the demikernel-ci.py script. It keeps one older version from the last run and creates a new directory with the test configuration (libos, branch, compile mode). It then names each of the log files after the test name and whether the host was the server or client and the hostname where it ran. This should make it easier to debug and sort through our testing logs.

[tools] Adding support for test directories and log files with hostnames

---

doc/testing.md
scripts/setup/debian.sh
tools/azure_tables.py
tools/demikernel_ci.py

This change adds support for running a suite of tests and reporting the results in Azure Tables. Summary of changes:
* Add installation of azure-data-tables python package. This is only needed on the machine running the tests, but I thought there was no harm installing it along with other dependencies.
* Demikernel CI python script changed to module. We can now include the CI script functionality in other files, especially the run_pipeline method, which can be used to trigger a specific set of tests. run_pipeline now returns a hashmap of test names and a boolean reflecting whether the test passed, instead of a packed bit string. 
* A new Azure Tables python script. This script takes a similar set of arguments to the CI script but additionally will take an Azure connection string and table …

[tools] Initial Azure Tables support

---

src/rust/runtime/memory/buffer/databuffer.rs
src/rust/runtime/memory/buffer/dpdkbuffer.rs

This resolves issue #377. The new DemiBuffer abstraction has replaced our older code and the old APIs should no longer be used. This marks the old APIs deprecated so we can move towards deleting them.

[memory] Marking old APIs as deprecated

---

src/rust/catcollar/futures/accept.rs
src/rust/catcollar/futures/mod.rs
src/rust/catcollar/mod.rs
src/rust/catloop/mod.rs
src/rust/catnap/futures/accept.rs
src/rust/catnap/futures/mod.rs
src/rust/catnap/mod.rs
src/rust/catnip/interop.rs
src/rust/catpowder/interop.rs
src/rust/inetstack/operations.rs
src/rust/inetstack/protocols/tcp/operations.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/tcp/tests/established.rs
src/rust/inetstack/protocols/tcp/tests/setup.rs
tests/rust/tcp.rs

This commit fixes https://github.com/demikernel/demikernel/issues/364
- Changed Futures system in all LibOSes to output the accepted IPv4 address.
- Fixed method for crafting a `demi_accept_result_t` in all LibOses.
- Fixed concerned unit tests.

[pdpix] Remote Address Is Not Set In `demi_accept_result_t`

---

src/rust/inetstack/protocols/udp/tests.rs
src/rust/runtime/queue/mod.rs
src/rust/runtime/queue/qdesc.rs

This PR closes https://github.com/demikernel/demikernel/issues/430.
- Changed `QDesc` to use a `u32` type representation for queue descriptors.
- Fixed `IoQueueTable` accordingly.
- Fixed concerned unit tests.

[runtime] 32-Bit Queue Descriptors

---

src/rust/runtime/queue/mod.rs

This PR fixes https://github.com/demikernel/demikernel/issues/449.
- Changed the `BASE_QD` constant to `500` which is less than `FD_SETSIZE`.

[runtime] Make `BASE_QD < FD_SETSIZE`

---

linux.mk

This PR closes https://github.com/demikernel/demikernel/issues/451
- Changed `install` rule to copy `default.yaml` when install artifacts as well.

[build] Copy `default.yaml` When Installing Artifacts

---

src/rust/inetstack/protocols/ipv4/datagram.rs

This PR removes some unnecessary parentheses that were causing a compiler warning.

[ipv4] Removed extraneous Parenthesis to Avoid Compiler Warning

---

README.md
doc/building.md
man/demi_init.md

- This PR closes https://github.com/demikernel/demikernel/issues/455
- Updated documentation to include `Catloop` and `Catnapw`.
- Added information on LibOS codenames.

[doc] Updating Build Instructions and Manual Pages

---

examples/rust/linux.mk
examples/tcp-accept/args.rs
examples/tcp-accept/client.rs
examples/tcp-accept/main.rs
examples/tcp-accept/server.rs
tools/demikernel_ci.py

This PR closes https://github.com/demikernel/demikernel/issues/478
- Introduced a system level test program for connection establishment
- Added the new test program as an optional system level test in `demikernel_ci`

[examples] Adding tcp-accept Program

---

examples/pipe-open/args.rs
examples/pipe-open/client.rs
examples/pipe-open/main.rs
examples/pipe-open/server.rs
examples/rust/linux.mk
src/rust/catmem/futures/pop.rs
src/rust/catmem/mod.rs
src/rust/catmem/pipe.rs
tools/demikernel_ci.py

This PR closes https://github.com/demikernel/demikernel/issues/480
- Added a new example application to expose https://github.com/demikernel/demikernel/issues/480.
- Added new example application to `demikernel_ci`.
- Added Pipe abstraction to Catmem LibOS.
- Fixed https://github.com/demikernel/demikernel/issues/480.

[catmem] Don't Close Pipe When EoF is Reached

---

src/rust/catnap/mod.rs

[catnap] Free queue descriptor on `close()`

---

src/rust/catcollar/mod.rs
src/rust/catcollar/queue.rs
src/rust/catloop/mod.rs
src/rust/catloop/queue.rs
src/rust/catmem/mod.rs
src/rust/catmem/queue.rs
src/rust/catnap/mod.rs
src/rust/catnap/queue.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/mod.rs
src/rust/inetstack/protocols/peer.rs
src/rust/inetstack/protocols/queue.rs
src/rust/inetstack/protocols/tcp/active_open.rs
src/rust/inetstack/protocols/tcp/established/mod.rs
src/rust/inetstack/protocols/tcp/mod.rs
src/rust/inetstack/protocols/tcp/operations.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/tcp/queue.rs
src/rust/inetstack/protocols/udp/mod.rs
src/rust/inetstack/protocols/udp/peer.rs
src/rust/inetstack/protocols/udp/queue.rs
src/rust/inetstack/test_helpers/engine.rs
src/rust/runtime/queue/mod.rs
src/rust/runtime/queue/qtype.rs

This change unifies all of the per-queue metadata for all libOSes into one IoQueueTable abstraction. The IoQueueTable is generic over the queue type, which is based on and implemented by the libOS. For libOSes with multiple queue types, an enum can be used to dispatch Demikernel calls to the appropriate queue type. Eventually, we expect this queue table to be shared across multiple libOSes, although right now, each libOS keeps it's own queue table.

[runtime] Unify Queue Table Abstraction

---

examples/rust/linux.mk
examples/tcp-bind/main.rs

This PR closes https://github.com/demikernel/demikernel/issues/501.

[examples] TCP Bind Application

---

src/rust/pal/linux/shm.rs

- This PR closes https://github.com/demikernel/demikernel/issues/504
- This PR closes https://github.com/demikernel/demikernel/issues/505
- Changed `SharedMemory::open()` to retrieve `errno` and propagate it on fail.
- Changed `SharedMemory:create()` to retrieve `errno` and propagate it on fail.

[pal] Retrieve `errno` and Propagate It in `SharedMemory`

---

src/rust/runtime/queue/mod.rs

This PR closes https://github.com/demikernel/demikernel/issues/507
- Added a new function `get_values()` to `IoQueueTable`.

[runtime] Iterator over IO Queue Table

---

src/rust/catnap/mod.rs
src/rust/catnap/queue.rs

This PR fixes https://github.com/demikernel/demikernel/issues/508
- Added extra check for whether the bind address is already in use.
- Fixed error value when trying to bind a bound socket to a different address from `EBADF` to `EINVAL`.
This PR takes dependency on https://github.com/demikernel/demikernel/pull/513

[catnap] Do not Allow Multiple `bind()` to Same Address

---

src/rust/catcollar/mod.rs
src/rust/catcollar/queue.rs

- This PR fixes https://github.com/demikernel/demikernel/issues/509
- This PR fixes https://github.com/demikernel/demikernel/issues/510
- Fixed check for bad `close()`
- Added extra check for whether the bind address is already in use.
- Fixed error value when trying to bind a bound socket to a different address from `EBADF` to `EINVAL`.
This PR takes dependency on https://github.com/demikernel/demikernel/pull/513

[catcollar] Do not Allow Multiple `bind()` to Same Address

---

src/rust/inetstack/protocols/tcp/peer.rs
tests/rust/tcp.rs

- This PR fixes https://github.com/demikernel/demikernel/issues/511
- This PR fixes https://github.com/demikernel/demikernel/issues/512
- Fixed `close()` to succeed when closing bound and unbound sockets
- Fixed test code to use `safe_close_active()` to correctly close active sockets.

[inetstack] Fail to Close Bound and Unbound Sockets

---

src/rust/catloop/duplex_pipe.rs
src/rust/catloop/futures/accept.rs
src/rust/catloop/futures/connect.rs
src/rust/catmem/mod.rs

This PR fixes several bug fixes that were exposed by the `tcp-accept` program https://github.com/demikernel/demikernel/issues/478.
- When closing duplex pipe, half-close underlying receiving pipe.
- Re-issue accept operation on bad connect request.
- Re-try on connection timeout.
- Half-Close duplex pipe when connecting.
- Wait for connect ACK when accepting a connection.

[catloop] Several Bug Fixes for Connection Establishment / Shutdown

---

src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
src/rust/inetstack/protocols/tcp/established/mod.rs
src/rust/inetstack/protocols/tcp/operations.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/udp/futures/operation.rs

This PR implements asynchronous close for the inet stack. Importantly, this PR creates a future/coroutine for driving the TCP connection to the close state and then freeing resources associated with the queue/socket. This PR leaves TODOs for actually implementing the TCP close state transitions for a later PR. Currently, the future immediately returns without being yielding, so there is no need to wake up the future. We will need to store a waker in the established socket, separate from the one for receiving data for close operations. Note that there is no need to free any of the socket data structures or control blocks explicitly because they are now all owned by the IoQueueTable, so when we free the queue descriptor, all associated metadata should be correctly freed as well. This means …

[inetstack] Implement async_close

---

examples/rust/linux.mk
examples/tcp-close/args.rs
examples/tcp-close/client.rs
examples/tcp-close/main.rs
examples/tcp-close/server.rs
examples/tcp-close/standalone.rs

This PR closes https://github.com/demikernel/demikernel/issues/526
- Added a standalone test that attempts to close an invalid socket.
- Added a standalone test that attempts to close a TCP socket that is not bound.
- Added a standalone test that attempts to close a TCP socket that is bound.
- Added a standalone test that attempts to close a TCP socket that is listening.
- Added a standalone test that attempts to close a TCP socket that is accepting.
- Added a standalone test that attempts to close a TCP socket that is connecting.
- Added a test that attempts to close a TCP socket that is connected.
```bash
export CONFIG_PATH=$HOME/config.yaml
export LIBOS=catnap|catcollar|catloop|catpowder|catnip
./bin/examples/rust/tcp-close.elf --address 127.0.0.1:12345 --run-mode standalone …
```

[examples] `tcp-close` Testing Program

---

tools/demikernel_ci.py

This commit partially addresses https://github.com/demikernel/demikernel/issues/544
- Added support for test aliases.
- Fully enabled `tcp-close` for Catnap LibOS (standalone, sequential and concurrent modes).
- Fully enabled `tcp-close` for Catcollar Libos (standalone, sequential and concurrent modes).
- Partially enabled `tcp-close` for Catloop Libos (sequential and concurrent modes).

[ci] Support `tcp-close` in `demikernel-ci`

---

src/rust/runtime/memory/demibuffer.rs

This PR closes https://github.com/demikernel/demikernel/issues/542
- Renamed `DemiBuffer::split_off()` to `DemiBuffer::split_back()`
- Improved documentation for `DemiBuffer::split_back()`
- Introduced `DemiBuffer::split_front()`
- Introduced a test unit for `DemiBuffer::split_front()`

[runtime] Improve Split Functionality in `DemiBuffer`

---

Cargo.toml
linux.mk
tests/rust/tcp-test/accept/mod.rs
tests/rust/tcp-test/args.rs
tests/rust/tcp-test/bind/mod.rs
tests/rust/tcp-test/close/mod.rs
tests/rust/tcp-test/connect/mod.rs
tests/rust/tcp-test/listen/mod.rs
tests/rust/tcp-test/main.rs
tests/rust/tcp-test/socket/mod.rs

- This PR partially addresses https://github.com/demikernel/demikernel/issues/554
- This PR partially addresses https://github.com/demikernel/demikernel/issues/549
- This PR partially addresses https://github.com/demikernel/demikernel/issues/526
- This PR partially addresses https://github.com/demikernel/demikernel/issues/501
- This PR partially addresses https://github.com/demikernel/demikernel/issues/567
- This PR partially addresses https://github.com/demikernel/demikernel/issues/566
Added the following integration tests for TCP `accept()`:
- Attempt to accept connections on an invalid queue descriptor
- Attempt to accept connections on a TCP socket that is not bound
- Attempt to accept connections on a TCP socket that is not listening
- Attempt to accept connections on a TCP socket …

[test] Integration Tests for TCP

---

scripts/config/default.yaml

This PR solves https://github.com/demikernel/demikernel/issues/536
Just append an empty string to `eal_init` in the `default.yaml` configuration file.

[catnip] Append an empty string at eal_init args to be skipped

---

src/rust/catnap/mod.rs
src/rust/catnap/queue.rs
src/rust/catnap/socket.rs

- This PR fixes several bugs in Catnap LibOS that were exposed by https://github.com/demikernel/demikernel/pull/562
- Introduced `Socket` abstraction
- It stores the state of a socket, as well as the local address to which a socket is bound and the remote address to which a socket is connected.
- It encodes error conditions when attempting to perform invalid transitions in the lifetime of a socket.
- Changed the `CatmemQueue` abstraction to use the `Socket` abstraction.
- Changed the PDPIX layer for `CatmemQueue` to use the `Socket` abstraction.

[catnap] Several Fixes Around Socket State

---

tests/rust/tcp-test/close/mod.rs
tests/rust/tcp-test/close/wait.rs

When we close a queue, all of the queues associated queue tokens should return from wait with an error code. This adds test case for that behavior.

[test] Add tests for wait after close

---

examples/tcp-echo/client.rs
examples/tcp-echo/main.rs
examples/tcp-echo/server.rs
tools/demikernel_ci.py

- This PR is a partial fix for https://github.com/demikernel/demikernel/issues/578
- Changed stop condition for TCP Echo server.
- Improved logs on TCP Echo application to use stdout and not conflict with stderr
- Enabled `tcp-echo` for Catap LibOS in `demikernel-ci`

[ci] Enable `tcp-echo` for Catnap LibOS

---

src/rust/catnap/mod.rs
tests/rust/tcp-test/bind/mod.rs
tests/rust/tcp-test/main.rs

- This PR closes https://github.com/demikernel/demikernel/issues/501
- This PR exposes https://github.com/demikernel/demikernel/issues/189
- This PR exposes https://github.com/demikernel/demikernel/issues/582
Added the following integration tests for TCP bind():
- Attempt to bind to the wildcard port.
- Attempt to bind to the wildcard address.
- Attempt to bind to the wildcard address and port.
- Attempt to bind to a non-local address.
- Attempt to bind a TCP socket that is closed.

[test] Integration Tests for TCP `bind()`

---

src/rust/catnap/mod.rs
tests/rust/tcp-test/listen/mod.rs

- This PR closes https://github.com/demikernel/demikernel/issues/566
- This PR exposes https://github.com/demikernel/demikernel/issues/584
Added the following integration tests for TCP `listen()`:
- Attempt to listen for connections on a TCP socket with a zero backlog length.
- Attempt to listen for connections on a TCP socket with an invalid backlog length.
- Attempt to listen for connections on a TCP socket that is closed.

[test] Integration Tests for TCP `listen()`

---

src/rust/lib.rs
tests/rust/tcp.rs
tests/rust/udp.rs

- This PR is a partial fix for https://github.com/demikernel/demikernel/issues/172
- Drop use of `new_uninit` unstable feature

[build] Drop Use of `new_uninit`

---

tests/rust/tcp-test/accept/mod.rs
tests/rust/tcp-test/close/async_close.rs
tests/rust/tcp-test/close/mod.rs
tests/rust/tcp-test/close/wait.rs
tests/rust/tcp-test/connect/mod.rs
tests/rust/tcp-test/listen/mod.rs

This PR closes issue #626. I removed 2 tests from the close and async_close tests because they are replicated by the wait after close tests. For example, close_accepting_socket and close_connecting_socket is now identical to wait_after_close_accepting_socket. There are additional tests that are duplicated, for example, accept_listening_socket is identical to wait_after_closing_accepting socket. Likewise, close_listening_socket is identical to listen_bound_socket. I chose not to remove those duplicates as they are in different modules and potentially serve different purposes, but I removed the duplicate tests that were all for close. Let me know if we want to do something else.

[test] Removing Scheduler Assumptions from Tests

---

src/rust/catloop/mod.rs

This PR closes https://github.com/demikernel/demikernel/issues/622
- Improved some error logs in Catloop LibOS
- Fixed collisions in queue token space of Catloop LibOS
- Queue tokens from Catmem LibOS are now registered in a different table

[catloop] Collisions on Queue Token Space

---

src/rust/catmem/mod.rs

This commit closes https://github.com/demikernel/demikernel/issues/589

[catmem] Redimensioning Ring Buffer

---

tests/rust/common/libos.rs
tests/rust/sga.rs
tests/rust/tcp.rs
tests/rust/udp.rs

This PR addresses #207 for our integration tests (i.e., everything under the tests/rust director). It aligns the TCP and UDP tests with the new TCP integration tests.

[test] Remove panic, expect and unwrap from integration tests

---

examples/tcp-close/args.rs
examples/tcp-close/client.rs
examples/tcp-close/main.rs
examples/tcp-close/server.rs
tools/demikernel_ci.py

[tcp-close] New whocloses semantics

---

examples/tcp-echo/client.rs
examples/tcp-echo/main.rs
examples/tcp-echo/server.rs

This PR removes any use of panic! from the tcp-echo system test in examples/tcp-close. Instead, we use bail! to fail gracefully and add tags for where open sockets or scatter-gather arrays should be closed/freed.

[test] Remove panics from tcp-echo system test

---

Cargo.toml
linux.mk
tests/rust/pipe-test/args.rs
tests/rust/pipe-test/create_pipe/mod.rs
tests/rust/pipe-test/main.rs
tools/demikernel_ci.py

This PR closes https://github.com/demikernel/demikernel/issues/615
- Added switch for integration tests in the build system.
- Run integration tests in TCP queues: `make test-integration-rust TEST_INTEGRATION=tcp-test ...`
- Run integration tests in pipe queues: `make test-integration-rust TEST_INTEGRATION=pipe-test ...`
- Added the following integration tests for `create_pipe()`:
- Attempt to create a pipe with an invalid name.
- Attempt to create two pipes with the same name.

[test] Integration Tests for TCP `create_pipe()`

---

examples/rust/udp-dump.rs
examples/rust/udp-echo.rs
examples/rust/udp-ping-pong.rs
examples/rust/udp-pktgen.rs
examples/rust/udp-push-pop.rs
examples/rust/udp-relay.rs

This PR removes panics (and unwrap and expects) from the UDP system tests in examples/rust/udp-*. It also links to a new issue for cleaning up state on error. It also replaces assert! with assert_eq!

[test] Remove panic from UDP system tests

---

src/rust/lib.rs

This PR introduces ensure_eq and ensure_neq, which are the equivalent of ensure for assert_eq and assert_neq. Since the anyhow crate doesn't support ensure_eq and ensure_neq, we have implemented it here for our use.

[test] Add `ensure_eq!` macro

---

tests/rust/pipe-test/create_pipe/mod.rs
tests/rust/pipe-test/main.rs
tests/rust/pipe-test/open_pipe/mod.rs

- This PR closes https://github.com/demikernel/demikernel/issues/616
- Added `test!()` helper macro that lunches a test a prints on the standard output if that test has passed or failed.
- Added `update_error!()` helper macro that updates an error variable with an error without overwriting previous error.
- Changed integration tests for `open_pipe()` to use the `test!()` and `update_error!()` helper macros.
- Added the following integration tests for `create_pipe()`:
- Attempt to open a pipe with an invalid name.
- Attempt to open a pipe that does not exist.
- Attempt to open open the same pipe multiple times.

[test] Integration Tests for TCP `open_pipe()`

---

src/rust/collections/intrusive/intrusive_queue.rs
src/rust/collections/raw_array.rs
src/rust/collections/ring.rs
src/rust/collections/shared_ring.rs

This PR addresses issue #207 for all of the unit tests in src/rust/collections. It also adds a return value to every test and replaces assert with ensure and assert_eq with the new ensure_eq macro.

[test] Remove panic from collections unit tests

---

src/rust/pal/linux/shm.rs
src/rust/perftools/profiler/tests.rs

This PR updates the unit tests in the pal and perftools directories to remove panics and asserts.

[test] Remove panic from pal and perftools unit tests

---

examples/c/pipe-ping-pong.c
examples/c/pipe-push-pop.c
examples/c/tcp-ping-pong.c
examples/c/tcp-push-pop.c
examples/c/udp-ping-pong.c
examples/c/udp-push-pop.c

This PR closes https://github.com/demikernel/demikernel/issues/152
- Modified system-level tests for the C API to enable constants be overridable by command line arguments.

[test] Rich CLI for C System Tests

---

examples/rust/udp-echo.rs
src/rust/catnap/socket.rs
src/rust/inetstack/protocols/tcp/tests/established.rs
src/rust/inetstack/protocols/tcp/tests/mod.rs
src/rust/inetstack/protocols/tcp/tests/setup.rs
src/rust/perftools/profiler/tests.rs
src/rust/runtime/memory/demibuffer.rs

This PR covers the following:
- Fixes and closes #674 
- Fixes a warning from an unused function in Catnap's new socket abstraction
- Fixes errors introduced by the new tests where we are not checking the outcome of some functions
- Fixes and closes #679 
These cleanups will make the build easier to understand by fixing and removing most spurious warnings.It removes a warning in catnap for an unused function

[test] Fix compiler errors and warnings

---

tests/rust/tcp-test/accept/mod.rs
tests/rust/tcp-test/bind/mod.rs
tests/rust/tcp-test/close/async_close.rs
tests/rust/tcp-test/close/mod.rs
tests/rust/tcp-test/connect/mod.rs
tests/rust/tcp-test/listen/mod.rs
tests/rust/tcp-test/socket/mod.rs

This PR replaces all asserts with demikernel::ensure_eq and removes some expect_err statements that would cause panics

[test] Remove assert from integration tests

---

tests/rust/tcp-test/accept/mod.rs
tests/rust/tcp-test/bind/mod.rs
tests/rust/tcp-test/close/async_close.rs
tests/rust/tcp-test/close/mod.rs
tests/rust/tcp-test/close/wait.rs
tests/rust/tcp-test/connect/mod.rs
tests/rust/tcp-test/listen/mod.rs
tests/rust/tcp-test/main.rs
tests/rust/tcp-test/socket/mod.rs

This PR switches the tests in tests/rust/tcp-test to use the new collect macro.

[test] Switch to collect macro for tcp integration tests

---

src/rust/catmem/mod.rs

This PR is a follow up of https://github.com/demikernel/demikernel/pull/686
- Changed `close()` to release the queue descriptor even if we fail to `push_eof()`.
https://github.com/demikernel/demikernel/pull/686

[catmem] Release Queue Descriptor Even If `close()` Fails

---

tests/rust/pipe-test/main.rs
tests/rust/pipe-test/wait/mod.rs

This PR partially addresses https://github.com/demikernel/demikernel/issues/619
- Added integration test for "attempt to wait on an invalid queue token".

[test] Wait on Invalid Queue Token Pipe

---

tests/rust/pipe-test/args.rs
tests/rust/pipe-test/main.rs
tests/rust/pipe-test/push_wait/client.rs

This PR partially addresses https://github.com/demikernel/demikernel/issues/619
- Fixed `push_wait` integration test to run the co-routine once before calling `close()`
- Added integration test for "attempt to wait for a `push()` operation to complete after asynchronously closing a pipe."

[test] Wait Push After Asynchronous Close

---

tests/rust/pipe-test/args.rs
tests/rust/pipe-test/main.rs
tests/rust/pipe-test/pop_wait/server.rs

This PR partially addresses https://github.com/demikernel/demikernel/issues/619
- Added integration test for "attempt to wait for a `pop()` operation to complete after asynchronously closing a pipe."

[test]  Wait Pop After Asynchronous Close Pipe

---

src/rust/lib.rs
tests/rust/pipe-test/async_close/mod.rs
tests/rust/pipe-test/close/mod.rs
tests/rust/pipe-test/create_pipe/mod.rs
tests/rust/pipe-test/main.rs
tests/rust/pipe-test/open_pipe/mod.rs
tests/rust/pipe-test/wait/mod.rs

This PR closes https://github.com/demikernel/demikernel/issues/687.
- Moved test macros to Demikernel source tree.
- Added `dump_test!()` macro.
- Renamed test macros.

[test] Test Macros for Demikernel

---

src/rust/catcollar/mod.rs
src/rust/catmem/futures/pop.rs
src/rust/catnap/coroutines/pop.rs
src/rust/catpowder/runtime/network.rs
src/rust/runtime/limits.rs
src/rust/runtime/mod.rs

This PR closes https://github.com/demikernel/demikernel/issues/698
- Added a system-wide constant for the maximum size of receive buffers.
- Changed Catnap LibOS to use that system-wide constant.
- Changed Catmem LibOS to use that system-wide constant.
- Changed Catcollar LibOS to use that system-wide constant.
- Changed Catpowder LibOS to use that system-wide constant.

[pdpix] Have a System-Wide Maximum Size for a Receive Buffer

---

src/rust/catcollar/mod.rs
src/rust/catloop/mod.rs
src/rust/catnap/mod.rs
src/rust/demikernel/libos/network.rs
src/rust/inetstack/mod.rs

This PR is a partial fix for https://github.com/demikernel/demikernel/issues/584
- Moved check logic for backlog length to PDPIX layer
- Added debug assert on Catnap LibOS for backlog length.
- Added debug assert on Catcollar LibOS for backlog length.
- Added debug assert on Catloop LibOS for backlog length.
It was not possible to fix this for Catpowder and Catnip because the legacy test infrastructure would fail. Once we have the new infrastructure enabled for them, we can have the issue closed.

[pdpix] Consistent Behavior When `listen()` with Invalid Backlog Length

---

src/rust/catcollar/mod.rs
src/rust/catloop/mod.rs
src/rust/catmem/mod.rs
src/rust/catnap/mod.rs
src/rust/demikernel/libos/mod.rs
src/rust/inetstack/mod.rs
src/rust/runtime/limits.rs

This PR closes https://github.com/demikernel/demikernel/issues/559
- Introduced `POP_SIZE_MAX` limit.
- Changed PDPIX layer to check size of pops.
- Changed Catnap LibOS to assert size of pops.
- Changed Catcollar LibOS to assert size of pops.
- Changed Catnip LibOS to assert size of pops.
- Changed Catpowder LibOS to assert size of pops.
- Changed Catloop LibOS to assert size of pops.
- Changed Catmem LibOS to assert size of pops.

[pdpix] Have an Upper Limit for Fixed-Size `pop()`s

---

examples/pipe-open/client.rs
examples/pipe-open/server.rs

This PR adds a drop function to both the server and client for proper cleanup and closes #638.

[test] Add drop function to pipe-open

---

src/rust/catnap/mod.rs

This PR close #668. I explicitly close each socket with a valid file descriptor. As an aside, we may want to move any code that only deals with a single queue or socket into the CatnapQueue or Socket data structure. For example, the RawFd associated with the socket should probably be stored inside the socket.

[catnap] Implement drop for cleanup on exit

---

src/rust/catloop/duplex_pipe.rs
src/rust/catnap/queue.rs
src/rust/demikernel/libos/mod.rs
src/rust/inetstack/mod.rs
src/rust/scheduler/handle.rs
src/rust/scheduler/scheduler.rs

This PR closes #624. 
Previously, we used the offset of the Task in the slab data structure as the key for uniquely identifying a scheduled task externally outside the scheduler. This PR changes the key to a token that is randomly allocated for each scheduled task. We introduce a tokens table to map from tokens to offsets (previously keys). Note the changes of variable names and function names, this was done intentionally to enforce the new data structures and to better describe the difference between tokens and offsets. I chose to specifically generate random tokens to keep applications from depending on qtokens in a way that is not opaque.
We chose to use another level of indirection to minimize changes to the scheduler. Eventually we may want to remove the PinSlab data structure. Note …

[PDPIX] Do not reuse qtokens

---

src/rust/catcollar/mod.rs
src/rust/catloop/duplex_pipe.rs
src/rust/catloop/futures/accept.rs
src/rust/catloop/mod.rs
src/rust/catmem/mod.rs
src/rust/catnap/mod.rs
src/rust/catnap/queue.rs
src/rust/catnip/mod.rs
src/rust/catpowder/mod.rs
src/rust/demikernel/libos/memory.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/arp/peer.rs
src/rust/inetstack/protocols/icmpv4/peer.rs
src/rust/inetstack/protocols/tcp/active_open.rs
src/rust/inetstack/protocols/tcp/established/mod.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/inetstack/protocols/udp/peer.rs
src/rust/scheduler/handle.rs
src/rust/scheduler/mod.rs
src/rust/scheduler/scheduler.rs

This PR closes #174. It renames the following variables to be more meaningful:
* SchedulerHandle -> TaskHandle
* id -> task_id
* offset -> index

[Runtime] Rename scheduler handle to task handle and other things to more useful things

---

examples/rust/pipe-ping-pong.rs

This PR refactors the pipe-ping-pong example and supports drop for closing the pipe queue descriptors.
Closes #721

[pipe-ping-pong] Refactor to add Drop

---

src/rust/catcollar/futures/accept.rs
src/rust/catcollar/futures/connect.rs
src/rust/catcollar/iouring.rs
src/rust/catcollar/mod.rs
src/rust/catcollar/runtime/mod.rs
src/rust/catloop/mod.rs
src/rust/catnap/coroutines/accept.rs
src/rust/catnap/coroutines/connect.rs
src/rust/catnap/coroutines/pop.rs
src/rust/catnap/coroutines/push.rs
src/rust/catnap/mod.rs
src/rust/catpowder/interop.rs
src/rust/pal/linux/mod.rs

This PR closes https://github.com/demikernel/demikernel/issues/134.
- Introduced utility function `socketaddrv4_to_sockaddr()`
- Introduced utility function `sockaddr_to_socketaddrv4()`
- Changed concerned code to only perform conversions from/to `SocketAddrV4` and `libc::sockaddr`

[pdpix] Fix Network Types to be Compatible With Each Other

---

src/rust/catloop/mod.rs

The message was misleading us to think that the client was invoking `accept()` in the logs.

[catloop] Warn msg correction

---

CONTRIBUTING.md
man/demi_init.md
src/rust/catloop/duplex_pipe.rs
src/rust/catnapw/futures/accept.rs
src/rust/catpowder/runtime/mod.rs
src/rust/demikernel/bindings.rs
src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
src/rust/runtime/memory/demibuffer.rs
src/rust/scheduler/scheduler.rs

1. Removed unnecessary call to `get_page_indices()` in the scheduler.
2. Removed unnecessary `mut` keywords from: a) inetstack, b) runtime. These were causing compiler warnings.

[cleanup] Remove unnecessary code

---

src/rust/catloop/duplex_pipe.rs
src/rust/catloop/futures/connect.rs

This PR is a workaround for https://github.com/demikernel/demikernel/issues/769

[catloop] Connection Establishment Does Not Cancel Inflight Pop Correctly

---

src/rust/inetstack/protocols/tcp/established/background/sender.rs
src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
src/rust/inetstack/protocols/tcp/established/sender.rs

Some TCP stacks may buffer received data until a segment is received with the PSH bit set. This PR modifies Demikernel's TCP stack to set the PSH bit when transmitting data to avoid high latencies when communicating with such TCP stacks. The PSH bit is only set on the final segment transmitted for each sent buffer.

[inetstack] Use TCP PSH bit

---

src/rust/scheduler/scheduler.rs

This PR fixes a rebase issue that overwrote a bug fix from PR #764 and it removes an infinite loop in the task allocation code.

[runtime] Fixing issues in scheduler

---

src/rust/catmem/futures/close.rs
src/rust/catmem/futures/mod.rs
src/rust/catmem/mod.rs
src/rust/demikernel/libos/memory.rs
src/rust/demikernel/libos/mod.rs
tests/rust/pipe-test/async_close/mod.rs
tools/demikernel_ci.py

- This PR closes https://github.com/microsoft/demikernel/issues/659.
- Implemented `async_close()` for Catmem LibOS
- Fixed async close tests on pipes
- Enabled standalone tests for Catmem LibOS

[catmem] Missing `async_close`

---

src/rust/inetstack/protocols/ipv4/datagram.rs
src/rust/inetstack/protocols/ipv4/tests.rs

This PR closes #781.
- Updated the upper bound of the for in the test_ipv4_header_parse_good test to include the value 15.
- Added the header length in the build_ipv4_header function.
- Verified the minimum size of the buffer in the compute_checksum function.

[test] Missing cases on IPv4 test-unit

---

src/rust/catloop/mod.rs

- This PR closes https://github.com/microsoft/demikernel/issues/786

[catloop] Missing to Shift Catmem Queue Tokens When Packing Result

---

src/rust/inetstack/protocols/icmpv4/datagram/header.rs
src/rust/inetstack/protocols/mod.rs

- This PR closes https://github.com/demikernel/demikernel/issues/205
- Created two auxiliary functions: `generic_checksum` and `fold16` to compute one's complement checksum;
- Updated ICMPv4, IPv4, UDP, and TCP protocols to use `generic_checksum` in parse and serialize functions.

[inetstack] Generic Checksum

---

src/rust/collections/shared_ring.rs

This PR closes https://github.com/microsoft/demikernel/issues/319.

[test] Add Barrier to Ring Buffer Test

---

src/rust/catloop/futures/accept.rs
src/rust/catloop/mod.rs

This PR closes #621
- Updated `CatloopLibOS` inserting the `EphemeralPorts` allocator.
- Allocated ports using the port allocator.
- Rollbacked the port allocation when the `accept` failed.
- Rollbacked the port allocation when the socket closed.

[catloop] Rollback Port Allocation

---

linux.mk
src/rust/catmem/futures/push.rs
tests/rust/pipe-test/pop_wait/client.rs
tests/rust/pipe-test/pop_wait/server.rs
tests/rust/pipe-test/push_wait/client.rs
tests/rust/pipe-test/push_wait/server.rs
tools/demikernel_ci.py

This PR turns on 4 tests: push-wait and pop-wait and push-wait-async and pop-wait-async. It also fixes a bug in catmem that causes the tests to fail and fixes some bugs in the tests themselves. I have turned off close for now due to an issue that will be fixed by issue #701

[tests] Turn on and fix Pipe Integration Tests

---

src/rust/catcollar/futures/connect.rs

This is a hotfix for recent bug that was triggered by some third-party crate that got updated.

[catmem] Broken Trace Statement

---

src/rust/catloop/futures/accept.rs

This PR removes the ability to ever ready from the control duplex pipe on the accept with anything other than the size of MAGIC_CONNECT. Because each MAGIC_CONNECT represents a separate connection request, the code will crash if we ever read more than one at a time. Thus, this PR closes #777 by simply removing the ability to read anything from the control duplex pipe that is not a single MAGIC_CONNECT value.

[catloop] Always Bound Read from Control Duplex Pipe

---

src/rust/scheduler/scheduler.rs

There was a double call to `tasks.remove()`. This PR removes the second call.

[scheduler] Avoid double remove()

---

src/rust/scheduler/handle.rs

We discussed offline that `TaskHandle.deschedule()` should be deprecated.

[scheduler] Deprecate TaskHandle.deschedule()

---

src/rust/catnap/socket.rs

This PR moves code that was dispersed into a more compact state machine. It closes #843

[catnap] Enhancement: More compact state machine code

---

src/rust/catcollar/mod.rs
src/rust/catloop/mod.rs
src/rust/catnap/mod.rs
src/rust/demikernel/libos/network.rs
src/rust/pal/constants.rs
tests/rust/tcp-test/listen/mod.rs

Making sure that the SOMAXCONN constant is available on Windows as well. It's not a part of libc (like on Linux).

[pal] Move SOMAXCONN to PAL

---

src/rust/runtime/queue/mod.rs

Adding `drain()` to `IoQueueTable`.

[runtime] Enhancement: drain for IoQueueTable

---

tools/ci/config/ci_map.yaml

This PR disables concurrent tests for Catloop LibOS as a workaround for https://github.com/microsoft/demikernel/issues/842

[ci] No Concurrency for Catloop LibOS

---

src/rust/catnap/mod.rs
src/rust/catnap/runtime.rs

This PR removes the public visibility of the scheduler in the runtime and adds functions for interacting with it instead. This is a first step towards having a unified runtime and scheduler across libOSes that is created at the Demikernel library level and passed into the constructor of every libOS.

[catnap] Encapsulate scheduler in runtime

---

src/rust/catmem/mod.rs
src/rust/catmem/queue.rs
src/rust/catmem/ring/mod.rs

This PR moves the catmem libOS closer to the Catnap architecture. It moves all state machine manipulation into the CatmemQueue and pushes some into the Ring data structure. It also moves to the unified Operation and OperationTask data types from the runtime.

[catmem] Move to catnap arch

---

src/rust/catloop/mod.rs
src/rust/catloop/runtime.rs
src/rust/catmem/mod.rs
src/rust/demikernel/libos/mod.rs

This PR moves Catmem onto the same scheduler as Catloop. It also unifies their memory runtimes into the DemiRuntime abstraction.

[catmem] Unify scheduler and memory runtime

---

examples/c/tcp-push-pop.c
man/demi_pushto.md

This PR fixes the doc and usage of `demi_pushto()`.

[test] Correct doc and usage of pushto

---

src/rust/catloop/mod.rs

This PR is a workaround for https://github.com/microsoft/demikernel/issues/189.

[catloop] `INADDR_ANY` Should Be Supported As The Wildcard Address

---

src/rust/catloop/mod.rs
src/rust/catloop/queue.rs
src/rust/catloop/socket.rs

This PR closes https://github.com/microsoft/demikernel/issues/829.

[catloop] Don't Allow `accept()` On A Socket That Is Already Accepting

---

src/rust/catnap/queue.rs
src/rust/inetstack/mod.rs
src/rust/scheduler/handle.rs
src/rust/scheduler/scheduler.rs

Partially addresses: #878
After this fix, there should be no `deprecated` warnings in the build log.

[src] Use FIXME comments instead of `deprecated` attribute

---

src/rust/catnap/queue.rs
src/rust/catnap/socket.rs
src/rust/runtime/network/socket/state.rs
tests/rust/tcp-test/wait/mod.rs

This is the first commit in a series that attempt to move async functions to standalone ones. This also enables us to move state machine transitions to the sockets level.

[catnap] Moving to Standalone Async Functions

---

src/rust/catmem/ring.rs
src/rust/collections/concurrent_ring.rs
src/rust/collections/mod.rs
src/rust/collections/ring.rs
src/rust/collections/shared_ring.rs

This PR implements the concurrent ring buffer detailed in issue #842 . It closes #818 and #842 . The file details the invariants that are preserved by the data structure, while allowing lock-free concurrent consumers and producers.

[collections]  Concurrent Ring Buffer

---

src/rust/catloop/mod.rs
src/rust/catloop/queue.rs
src/rust/catloop/runtime.rs

This PR moves Catloop to using a shared IoQueueTable inside DemiRuntime

[catloop] Move IoQueueTable 

---

src/rust/catmem/queue.rs
src/rust/catmem/ring.rs
src/rust/collections/concurrent_ring.rs

This PR adds the following improvements:
- Squashes `try_push`, `try_pop` and `try_close` functions.
- Changed ring to use full name
Motivation for first point:  When refactoring, we created private, one-line-functions for scoping. I merged these and fixed scoping rules to easy navigation across layers.

[catmem] Use Full Ring Name

---

examples/rust/pipe-ping-pong.rs
examples/rust/pipe-push-pop.rs
src/rust/catmem/mod.rs

This PR closes #894.
Commits:
- 323979bd4310fbc0ae53904579e7f8a433ad5c47 - Inserting the profiler annotations.
- c6943e6b94fab5705af7688d840b96eb369a051a - Updating the pipe-push-pop example.
- 155259014b515ff4f0f0f98e697705a8c448a84c - Updating the pipe-ping-pong example.

[catmem] Performance counters

---

src/rust/catloop/socket.rs
src/rust/runtime/network/socket/state.rs

This PR introduces a check for the accepting state on the `accept()` async path.

[catloop] Ensure Accepting in `accept`

---

src/rust/catmem/ring.rs
src/rust/runtime/network/ring/state.rs

This PR adds checks for push and pop aynsc paths.
Note that this PR also adds a workaround for https://github.com/microsoft/demikernel/issues/916

[catmem] Checks for Push and Pop

---

src/rust/catloop/mod.rs
src/rust/catloop/socket.rs
src/rust/catmem/mod.rs
src/rust/catnap/mod.rs
src/rust/runtime/mod.rs

This PR introduces a ref counted shared object that can be used for shared state without dynamic borrowing. The object lives as long as there are references (as there is an Rc inside); however it allows both multiple read and write references to the shared object. This object can be safely used as long as the code among which it is shared (e.g., different libOSes, different coroutines within the same libOS) never run concurrently. As Demikernel is currently single threaded and our scheduler can only run one coroutine at a time, this abstraction is safe to use throughout the code for shared references to libOSes, queues and runtimes. This data structure will continue to be safe if we use a multi-kernel architecture for multi-cores and run one instance of the libOSes per core and do not …

[runtime] New shared object for shared state

---

src/rust/catnap/mod.rs
src/rust/catnap/queue.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network.rs
src/rust/runtime/mod.rs

This PR removes all of the dynamic borrows in Catnap and replaces them with our new SharedObject abstraction. We rename the shared state objects to SharedCatnapLibOS and SharedCatnapQueue to indicate that they are shared across coroutines.

[catnap] Remove all Rc<RefCell> and replace with SharedObject

---

linux.mk

This PR updates [linux.mk](https://github.com/microsoft/demikernel/blob/dev/linux.mk) file allowing to use the `mlx5` driver on ConnectX-6 NICs.

[makefile] Allowing mlx5 driver for ConnectX-6 NICs

---

src/rust/catloop/mod.rs
src/rust/catloop/socket.rs
src/rust/catmem/mod.rs
src/rust/catnap/mod.rs
src/rust/demikernel/libos/mod.rs
src/rust/runtime/mod.rs

This PR adds Shared to the DemiRuntime to indicate that it is a SharedObject across coroutines.

[runtime] Enhancement: Add Shared to variable name

---

include/demi/types.h

Localize packing compiler directives for Windows builds. If this is not done, the packing directives will remain active for other build targets as well. So, to avoid this in integration builds (e.g., Bing), localizing the directives is the best option.

[demikernel] Localize packing compiler directives for Windows builds

---

src/rust/catloop/socket.rs

This PR fixes the buggy scenario where we should rollback the socket state if accept fails. Before we wouldn't do that, leaving the socket in a bad state.

[catloop] Rollback If Close Fails

---

src/rust/catloop/mod.rs
src/rust/catloop/queue.rs
src/rust/catloop/socket.rs

This PR closes #697.
We currently ignore the backlog length and this PR improves existing code by keeping track of pending connections and triggering logging if a passive socket is too busy.
Ideally we would send `ECONNREFUSED` back to clients, but the current connection handshake protocol does not support that. It will keep queueing requests anyways.

[catloop] Warn Backlog Length Listen

---

src/rust/catnip/interop.rs
src/rust/pal/functions.rs

Removed reference to the CHAR type on Windows. This also allows to unify the sin_zero initialization for Linux and Windows.

[demikernel] Enhancement: Remove refs to CHAR type

---

Cargo.toml

This PR updates the commit ID that the Demikernel repo points to in the dpdk-rs repo. The updated commit has changes required to build on Windows.

[catnip] Update pointer to dpdk-rs

---

src/rust/catnap/socket.rs

Handle error codes from `connect()` correctly on Windows catnap.

[catnap] Handle win connect error codes correctly

---

src/rust/catcollar/mod.rs
src/rust/catcollar/runtime/mod.rs
src/rust/catloop/mod.rs
src/rust/catmem/mod.rs
src/rust/catnap/mod.rs
src/rust/inetstack/test_helpers/runtime.rs
src/rust/runtime/mod.rs
src/rust/scheduler/scheduler.rs

This PR removes all refcells from the scheduler, as the scheduler is always part of a shared object now and no longer needs to be cloneable.

[runtime] Remove all Refcell from scheduler

---

src/rust/catnip/interop.rs
src/rust/catnip/mod.rs
src/rust/catnip/runtime/memory/manager.rs
src/rust/catnip/runtime/mod.rs
src/rust/catnip/runtime/network.rs

This PR removes the remaining inner construct from Catnip. It was originally used to share the DPDK memory manager in Catnip but I have moved the entire DPDKRuntime to a shared object instead.

[catnip] Remove inner construct from memory management runtime

---

src/rust/scheduler/scheduler.rs

The waker page offset does not need to be computed twice in this case.

[scheduler] Remove redundant waker page offset calculation

---

src/rust/catcollar/mod.rs
src/rust/catcollar/runtime/mod.rs
src/rust/demikernel/libos/mod.rs
src/rust/inetstack/test_helpers/runtime.rs
src/rust/runtime/mod.rs
src/rust/runtime/queue/mod.rs
tests/rust/common/libos.rs

This PR does some clean up inside the DemiRuntime needed to move the inetstack to a more object-oriented architecture. 
1. Move to a default constructor. This will let us add more data structures to the shared runtime, like the ephemeral port allocator without adding a lot of new code.
2. Move Catcollar to the shared runtime. This will let us get rid of the references to the io queue table and scheduler that do not go through the SharedDemiRuntime

[catcollar] Move to SharedDemiRuntime

---

src/rust/catloop/mod.rs
src/rust/inetstack/protocols/ip/mod.rs
src/rust/inetstack/protocols/peer.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/udp/peer.rs
src/rust/runtime/mod.rs
src/rust/runtime/network/ephemeral.rs
src/rust/runtime/network/mod.rs

This PR moves the ephemeral port allocator into the SharedDemiRuntime to avoid collisions when running more than one libOS. It also removes a lot of extraneous code and extra dependencies because the ephemeral port allocator is not in the inetstack any longer.

[runtime] Enhancement: Move ephemeral port allocator into shared runtime

---

src/rust/runtime/network/socket/mod.rs

I added a file descriptor to the socket id data structure for demuxing from incoming I/O but it is not platform-agnostic.

[runtime] Remove file descriptor from socket id data structure

---

src/rust/collections/mod.rs
src/rust/collections/ring.rs
src/rust/collections/shared_ring.rs

This PR includes the following enhancements:
- Refactors the `RingBuffer` class to operate more like a pipe: once instantiated, it may be `open`ed to produce a `(RingProducer, RingConsumer)` pair. These classes have the respective enqueue/dequeue operations exposed.
- Adds a type class constraint for the size pointers in `RingBuffer`. As a compelling example, XDP requires ring buffers to use 32-bit sizes.
- Creates the trait `IntSize` which allows `RingBuffer` to juggle various size types (no wider than usize).
- Changes the memory ordering to release-acquire semantics, which are fully sufficient for a SPSC model.
- Re-exposes the ring as a public export from collections mod.

[collections] Enhancement: refactor RingBuffer to operate more like a pipe

---

src/rust/runtime/network/ephemeral.rs

I added a constant that is only used for debug builds, so we are getting an unused code warning on release builds.

[runtime] Enhancement: Remove a warning

---

src/rust/catloop/mod.rs
src/rust/catnap/mod.rs

Do nothing for Close because it's not registered. This is done because we don't want to allow canceling the Close op as that may leave dangling resources.

[catloop] Do not remove pending op for Close

---

src/rust/inetstack/protocols/arp/peer.rs
src/rust/inetstack/protocols/icmpv4/peer.rs
src/rust/inetstack/protocols/tcp/active_open.rs
src/rust/inetstack/protocols/tcp/established/background/acknowledger.rs
src/rust/inetstack/protocols/tcp/established/background/mod.rs
src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs
src/rust/inetstack/protocols/tcp/established/background/sender.rs
src/rust/inetstack/protocols/tcp/established/mod.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/runtime/timer.rs
src/rust/scheduler/handle.rs
src/rust/scheduler/scheduler.rs

Because all of the yielders in a single coroutine share a waker bit, we are prone to spurious wake ups when a coroutine becomes runnable. Specifically, we cannot distinguish between timeouts and watched values changing, causing us to send acks and retransmits far too frequently.

[inetstack] Remove spurious wake ups

---

src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/tcp/active_open.rs
src/rust/inetstack/protocols/tcp/established/mod.rs
src/rust/inetstack/protocols/tcp/established/sender.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/tcp/queue.rs
src/rust/inetstack/protocols/tcp/tests/established.rs
src/rust/inetstack/protocols/tcp/tests/setup.rs
src/rust/inetstack/test_helpers/engine.rs
tests/rust/tcp.rs

This PR moves the TCP portion of the inetstack to a more object oriented architecture. This move will enable us to eventually shared code between the libOSes for queues and the socket state machine.

[inetstack] Move TCP stack to objects

---

src/rust/collections/async_queue.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/arp/peer.rs
src/rust/inetstack/protocols/icmpv4/peer.rs
src/rust/inetstack/protocols/tcp/active_open.rs
src/rust/inetstack/protocols/tcp/established/background/sender.rs
src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/inetstack/protocols/udp/peer.rs
src/rust/inetstack/protocols/udp/queue.rs
src/rust/inetstack/protocols/udp/tests.rs
src/rust/inetstack/test_helpers/engine.rs

This PR moves the UDP stack towards our new architecture. We have moved functionality into each SharedUDPQueue, including a per-queue background coroutine that sends pending packets. Since most of the time we will be able to send synchronously, it's better to avoid the lookup on each send and just rely on the scheduler to wake the appropriate background coroutine. I also added a clean up for the background coroutine on socket close.
This PR has a few lingering issues: 
1. I moved the UDP queues to the AsyncQueue data structure, which is currently unbounded. We should move it back to being bounded and possibly using the mpsc abstractions from the futures crate. We should decide what kind of blocking behavior we want when the receive or send queues fill up.
2. I added a SharedAsyncQueue …

[inetstack] Move UDP stack to objects

---

src/rust/catnip/mod.rs
src/rust/catpowder/mod.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/tcp/queue.rs
src/rust/inetstack/protocols/tcp/tests/established.rs
src/rust/inetstack/protocols/tcp/tests/setup.rs
src/rust/inetstack/test_helpers/engine.rs
src/rust/runtime/mod.rs
tests/rust/tcp.rs

This PR moves the TCP portion of the inetstack to using the shared state machine that is in the runtime. A few important things to note:
1. The TCP queue is now maintaining 2 state machines. We should deduplicate this and I have filed an issue to track it #1007.
2. This PR moves the inetstack closer to the same architecture as Catnap with functions passed in that move the state machine forward/rollback when there are errors (e.g., we were not able to insert the coroutine into the scheduler).  
3. This PR has added a list of pending ops to the TCP queue. However, because the packing for each returned result is in the libOS, I cannot remove the operation from the pending list. I think this will be resolved with #888 however.
4.  To align with Catnap, we now return queue tokens on …

[inetstack] Move TCP stack to use shared state machine

---

tools/ci/config/ci_map.yaml

This PR turns on TCP echo tests with a single client for Catnip and Catpowder.

[testing] Turn on TCP echo tests for inetstack

---

.github/workflows/catnapw.yml
tools/demikernel_ci.py
windows.mk

This PR closes https://github.com/microsoft/demikernel/issues/1031.
Please, consider this a draft integration.
- https://github.com/microsoft/demikernel/issues/1030
- https://github.com/microsoft/demikernel/issues/1033
- https://github.com/microsoft/demikernel/issues/1036

[test] Integrate Catnap Windows on CI Tool and Infrastructure

---

src/rust/catcollar/mod.rs
src/rust/catloop/mod.rs
src/rust/catloop/queue.rs
src/rust/catloop/socket.rs
src/rust/catnap/mod.rs
src/rust/catnap/queue.rs
src/rust/catnip/mod.rs
src/rust/catpowder/mod.rs
src/rust/runtime/mod.rs

Currently, pending ops management is done at the LibOS level. This has caused duplication of the hashmap datastructure and the associated management code in the `queue`, which decides when pending ops are added/removed/canceled.
After this change, the {qd -> {task_handle -> yielder_handle}} mappings will reside in the `runtime`, instead of the LibOS. This allows better tracking of yielder_handles and pending_op management in a cleaner manner. Another advantage of doing this is that the LibOS does not need to keep track of pending ops and cancellations. Additionaly, the coroutine constructors are simpler now because they don't need a `yielder` to be passed in any longer, so the `queue` does not need to create yielders.
This PR covers the following changes
- [runtime]
- Simplifies …

[demikernel] Improve pending_ops lifecycle management

---

src/rust/catnap/mod.rs

Currently, the `async_close()` does not track pending_op, and this change is to enable that tracking.

[catnap] Track pending_op for async_close

---

src/rust/runtime/network/ephemeral.rs

This PR closes https://github.com/microsoft/demikernel/issues/1039
- Included last port in the allocator
- Changed shuffling to occur only on release mode
- Cleaned up dead code

[runtime] Ephemeral Allocator Misses to Allocate Last Port on Private Range

---

src/rust/catloop/socket.rs
src/rust/catnap/queue.rs
src/rust/inetstack/protocols/tcp/queue.rs
src/rust/runtime/network/socket/operation.rs
src/rust/runtime/network/socket/state.rs
tests/rust/tcp-test/accept/mod.rs
tests/rust/tcp-test/listen/mod.rs

To begin unifying the state machines between the libOSes and runtime, I have simplified the state machine to only the states that require changes between the metadata state. Further, I have removed the rollback states (as they will not be able to also hold metadata) and simplified error handling by having the libOSes move the state machine to the closed state for now. We can revisit this decision later after we have integrated the inetstack into the state machine. This PR closes #1035

[runtime] Simplify state machine

---

src/rust/inetstack/protocols/tcp/peer.rs

This PR fixes the single non-passing test in the integration tests for bind. This closes #1010

[inetstack] Check for non-local address

---

src/rust/inetstack/protocols/tcp/active_open.rs
src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
src/rust/inetstack/protocols/tcp/established/mod.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/tcp/queue.rs
src/rust/inetstack/protocols/tcp/tests/setup.rs

This PR is a step towards having a linear flow for all of our TCP state machines by doing the following:
1. Using the connect coroutine to directly drive retries of SYN send instead of another background coroutine.
2. Directly moving the TcpHeader/packet to the module where it will be processed rather than borrowing it in the receive path. The receive path simply pushes the packet into an AsyncQueue, while the connect coroutine waits on arriving packets. The connect coroutine will then wake up and process the incoming packet.
3. The flow of connect is not changed too much because it only requires waiting on one packet. The utility of this architecture will be clear once we are performing part of the architecture with more steps. Here we are mostly getting rid of the extra coroutine.

[inetstack] Remove background coroutine from active connect

---

src/rust/catloop/queue.rs
src/rust/catloop/socket.rs
src/rust/catmem/queue.rs
src/rust/catnap/queue.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/tcp/queue.rs

This PR moves the tcp pending ops mgmt to the runtime.
Please keep in mind that the synchronous `close()` path will soon be removed from the codebase.

[inetstack] Move tcp pending ops mgmt to runtime

---

src/rust/inetstack/protocols/tcp/tests/established.rs
src/rust/inetstack/test_helpers/engine.rs

This PR changes the tcp test engine to use `async_close()` rather than `close()`.

[test] Use TCP Async Close in Test Engine

---

examples/tcp-close/args.rs
examples/tcp-close/client.rs
examples/tcp-close/helper_functions.rs
examples/tcp-close/main.rs
examples/tcp-close/server.rs

This PR:
- Removes synchronous close from the `tcp-close` example.
- Moves common code to a helper functions module.
This is a part of the series of PRs aimed towards removing synchronous `close()` from Demikernel.

[examples] Remove should_async_close flag from tcp-close

---

src/rust/catcollar/mod.rs
src/rust/catloop/mod.rs
src/rust/catloop/queue.rs
src/rust/catloop/socket.rs
src/rust/catmem/mod.rs
src/rust/catnap/mod.rs
src/rust/catnip/mod.rs
src/rust/catnip/runtime/memory/mod.rs
src/rust/catpowder/mod.rs
src/rust/demikernel/libos/memory.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network.rs
src/rust/inetstack/mod.rs
src/rust/runtime/memory/mod.rs

This PR removes the following functions from the libOSes and directly calls the runtime:
* poll 
* schedule/from_task_id
* pack_result
* sgaalloc
* sgafree
Note that we have not moved the sgaalloc and free functions for the libOSes that need special memory. I have filed an issue for that: https://github.com/microsoft/demikernel/issues/1057

[runtime] Enhancement: Use runtime instead of libos

---

src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/arp/peer.rs
src/rust/inetstack/protocols/arp/tests.rs
src/rust/inetstack/test_helpers/engine.rs

For the inetstack, we want to unwrap and turn the state machine operations into a linear flow. In order to accommodate this, we need to move away from a polling receive model where we always call the receive function from the top every time. Instead, we will simply insert the new packet into an AsyncQueue and the inetstack will pick up that packet from wherever in the linear flow it is blocked. This also means that the receive function will not return a result because it does not know if the inetstack will drop the packet. 
This change impacts the ARP cache very little since it does not have a state machine and does not really flow through a protocol. It will be more important for TCP, especially during connection set up and close, when we are waiting for very specific next packets.

[inetstack] Move ARP cache to background polling model

---

src/rust/demikernel/libos/memory.rs
src/rust/demikernel/libos/mod.rs

This PR removes the ability to call synchronous close() on catmem via the Demikernel API.
Incremental PR based on this PR https://github.com/microsoft/demikernel/pull/1064.

[catmem] Remove external support for synchronous close()

---

src/rust/collections/async_queue.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/peer.rs
src/rust/inetstack/protocols/tcp/active_open.rs
src/rust/inetstack/protocols/tcp/established/background/mod.rs
src/rust/inetstack/protocols/tcp/established/mod.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/tcp/queue.rs
src/rust/inetstack/protocols/tcp/tests/established.rs
src/rust/inetstack/protocols/tcp/tests/setup.rs
src/rust/inetstack/protocols/tcp/tests/simulator.rs
src/rust/inetstack/protocols/udp/peer.rs
src/rust/inetstack/protocols/udp/queue.rs
src/rust/inetstack/protocols/udp/tests.rs
src/rust/inetstack/test_helpers/engine.rs

This PR moves the remainder of the inetstack to AsyncQueues and doing network processing in a background coroutine instead of directly in the receive function. A few things to note:
1. We can no longer tell if the inetstack will drop the packet in the receive path. We need to wait for the stack to pick it up from the AsyncQueue and process it. This makes sense because whether the packet is valid depends on what state the inetstack is in. 
2. We use to check the state of the inetstack (or not check it if we decided it would be too expensive). Now the state of the inetstack will be encoded in the async coroutine and where it is blocked.
3. Because the receive path can no longer tell you if the packet will be dropped, some of our tests no longer work. I have filed an issue for this, but I …

[inetstack] Move TCP to receive polling coroutine

---

Cargo.toml
examples/rust/tcp-push-pop.rs
scripts/config/default.yaml
src/rust/catnap/mod.rs
src/rust/catnap/win/config.rs
src/rust/catnap/win/error.rs
src/rust/catnap/win/overlapped.rs
src/rust/catnap/win/socket.rs
src/rust/catnap/win/transport.rs
src/rust/catnap/win/winsock.rs
src/rust/runtime/mod.rs

This PR adds a Windows transport implementation to the catnap libos based on overlapped I/O. The implementation uses a single I/O completion port which is polled by a background coroutine. This allows coroutines to be written on top of overlapped I/O using the `IoCompletionPort::do_io` and `do_io_with` methods. This PR additionally contains extensive logic for translating Win32 error, Winsock error, and NTSTATUS codes into errno error codes. As such, I removed the common references to Windows error codes, as in `DemiRuntime::should_retry`.

[catnap] Enhancement: add overlapped I/O implementation for Windows

---

src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/tcp/established/background/mod.rs
src/rust/inetstack/protocols/tcp/established/background/sender.rs
src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
src/rust/inetstack/protocols/tcp/established/mod.rs
src/rust/inetstack/protocols/tcp/established/sender.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/tcp/queue.rs
tests/rust/tcp.rs
tests/rust/udp.rs

This PR moves the TCP close protocol to a linear flow and cleans up background tasks once we move out of the established state, closing #988

[inetstack] Move TCP close to a linear flow and remove synchronous close

---

src/rust/catcollar/mod.rs
src/rust/catloop/mod.rs
src/rust/catmem/mod.rs
src/rust/catnap/mod.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/udp/peer.rs
src/rust/runtime/mod.rs

This PR removes the Yielder and YielderHandle creation from the LibOS level and now does it at a centralized place in the runtime.
It only focuses on the LibOS level.
- This PR is not applicable for background coroutines.
- Does not cover the complete inetstack.

[demikernel] Consolidate yielder creation for all LibOS coroutines

---

nettest/input/accept-syn-carrying-data.pkt
src/rust/inetstack/protocols/tcp/passive_open.rs

- This PR closes https://github.com/microsoft/demikernel/issues/238
- This PR opens https://github.com/microsoft/demikernel/issues/1115
- Added a warn message on data drop for data carrying, SYN segments.
- Added test case for connection establishment with a data-carrying, SYN segment.

[inetstack] Add Warning Message on Data Drop for Data Carrying, SYN Segment

---

src/rust/catcollar/mod.rs
src/rust/catloop/mod.rs
src/rust/catmem/mod.rs
src/rust/catnap/linux/transport.rs
src/rust/catnap/win/overlapped.rs
src/rust/catnap/win/transport.rs
src/rust/demikernel/libos/network/libos.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/arp/peer.rs
src/rust/inetstack/protocols/icmpv4/peer.rs
src/rust/inetstack/protocols/tcp/established/mod.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/runtime/mod.rs
src/rust/runtime/queue/mod.rs
src/rust/runtime/scheduler/scheduler.rs
src/rust/runtime/scheduler/task.rs

This PR moves the scheduler and tasks to using FusedFutures instead of the basic Futures. Our scheduler notes the first time that a Task returns Ready and marks it as completed and never schedules it again. So if the future is not fused, it'll still never get polled again. [See this line of code](https://github.com/microsoft/demikernel/blob/647d0200e3266196d6adbedac703e7b79e198723/src/rust/runtime/scheduler/page/page.rs#L60).
Furthermore, our TaskWithResult type will have stored the output of the coroutine and will never invoke it again.[See here](https://github.com/microsoft/demikernel/blob/647d0200e3266196d6adbedac703e7b79e198723/src/rust/runtime/scheduler/task.rs#L101).
Thus, we should use FusedFutures to enforce that none of the futures that our scheduler operate on are able to run …

[runtime] Move to FusedFuture

---

src/rust/demikernel/libos/network/libos.rs
src/rust/inetstack/protocols/tcp/peer.rs

This PR closes https://github.com/microsoft/demikernel/issues/236
Added required logic to rollback ephemeral port allocation.

[inetstack] Free Ephemeral Ports Once Connection is Closed

---

src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
src/rust/inetstack/test_helpers/engine.rs
src/rust/runtime/mod.rs
tests/rust/common/libos.rs
tests/rust/tcp.rs
tests/rust/udp.rs

This PR closes https://github.com/microsoft/demikernel/issues/1120
- Fixed `remove_coroutine()`
- Fixed `wait()` to behave as it should and tests accordingly.
- Cleaned up "debug" traces on network stack.
- Added more useful trace statements on network stack.

[runtime] `remove_coroutine()` Doesn't Remove Completed QTokens from Pending Ops

---

src/rust/catnap/win/overlapped.rs
src/rust/collections/id_map.rs
src/rust/collections/mod.rs
src/rust/collections/pin_slab.rs
src/rust/runtime/queue/qtoken.rs
src/rust/runtime/scheduler/scheduler.rs

This PR adds a new data structure that is explicitly for us to enforce ID translations between internal data structures and external ones. Generally this takes the form of translating from something that we may hand to the application (e.g., a queue token) to an internal representation (e.g., an offset into a slab). Since slab offsets are often allocated sequentially, we do not want external applications or even the libOSes to depends on their specific characteristics. 
To deal with this, we introduce an IdMap data structure. It is explicitly used for translating between external and internal identifiers. On debug builds, this data structure randomly generates IDs and uses a hash map to map external to internal identifiers to enforce that there are no weird dependencies on IDs. On release …

[collections] Enhancement: External to internal ID map

---

src/rust/catnap/win/overlapped.rs
src/rust/collections/pin_slab.rs
src/rust/runtime/mod.rs
src/rust/runtime/queue/qtoken.rs
src/rust/runtime/scheduler/group.rs
src/rust/runtime/scheduler/mod.rs
src/rust/runtime/scheduler/scheduler.rs
src/rust/runtime/scheduler/task.rs

This PR adds the ability to create new task groups and assign tasks to them. Eventually we will likely create one task group for background coroutines and then one for each Demikernel queue. However, currently we only have one default group and we add all tasks to this group.
For our two benchmark tests, here are the changes in performance for a release build. Each run 5 times and averaged.
| | dev | this PR|
|--|--|--|
|benchmark_insert|330ns| 444ns|
|benchmark_poll|33ns|29ns|
Insertion has gone up 35%, however polling has gone down 12%. This seems like a reasonable trade-off as polling is done more frequently. I suspect the polling changes are due to polling the futures in a tighter loop after collecting all of the ready bits. I did not think it was worth digging deeper into the costs, …

[runtime] Enhancement: Add scheduler groups

---

src/rust/demikernel/libos/memory.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network/mod.rs

This PR moves the wait_* into the network and memory libOSes so that we can eventually get rid of poll and get_result. See #1128

[libos] move wait functions into libos

---

src/rust/catloop/socket.rs
src/rust/catnap/win/overlapped.rs
src/rust/demikernel/libos/memory.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network/mod.rs
src/rust/inetstack/protocols/tcp/tests/simulator.rs
src/rust/inetstack/protocols/udp/tests.rs
src/rust/inetstack/test_helpers/engine.rs
src/rust/runtime/mod.rs
src/rust/runtime/scheduler/group.rs
src/rust/runtime/scheduler/page/page.rs
src/rust/runtime/scheduler/scheduler.rs
src/rust/runtime/scheduler/task.rs
src/rust/runtime/scheduler/waker64.rs
tests/rust/common/libos.rs
tests/rust/tcp-test/accept/mod.rs
tests/rust/tcp-test/wait/mod.rs
tests/rust/tcp.rs
tests/rust/udp.rs

This PR closes #1128 . We move away from a polling model to directly return completed tasks after running the scheduler. We also immediately remove completed tasks (since they will never run again) and it is the responsibility of the higher-level runtime to stash them somewhere. Thus, now the runtime contains a wait function that runs the scheduler until the requested queue token has completed. This also moves us towards a model where we can unify timeouts for wait calls and background coroutines.
Note that this PR introduces mandatory time outs for everything in the libOS, ensuring that we are never wedged in Demikernel. However, it does require us to set these defaults, which might need to be adjusted and should probably eventually be moved to a single place.

[runtime] Remove poll and check completed in scheduler

---

src/rust/demikernel/libos/network/mod.rs
src/rust/inetstack/test_helpers/runtime.rs
src/rust/runtime/mod.rs

- Removed unused testing functions
- Changed time update methodology in some libOSes to avoid a system call to be invoked.

[runtime] Change Time Update Methodology in Some LibOSes

---

src/rust/catnap/win/overlapped.rs

This PR fixes a use-after-free when cancelling I/O operations on Windows. As noted in the added comment, the exact semantics of CancelIoEx on Windows are unclear w.r.t. the completion port. This could result in memory leaks. Tracking the OVERLAPPED objects in a table may allow us to more accurately own/free these.

[catnap] Fix use-after-free related to I/O cancellation in catnap for Windows

---

include/demi/wait.h
man/demi_wait.md
src/rust/demikernel/bindings.rs
src/rust/demikernel/libos/memory.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network/mod.rs
tests/c/syscalls.c

This PR drops support for `timedwait()` system call.

[demikernel] Drop `timedwait()`

---

src/rust/catnap/win/config.rs
src/rust/catnap/win/socket.rs
src/rust/catnap/win/transport.rs

This PR allows configuring Nagle's algorithm (i.e. TCP_NODELAY socket option) via a "use_nagle" config in config.yaml. I also refactored some of the Catnap/win/config.rs because the `require_option...` contradiction was bothering me.

[catnap] Enhancement: allow configuring Nagle's algorithm for TCP on Windows

---

src/rust/catloop/socket.rs
src/rust/catloop/transport.rs

This PR removes all calls to wait and uses of the demi_sgarray_t from the Catloop libOS. Instead it moves it completely to using coroutines and directly calling asynchronous Catmem functions. This is important because it keeps our scheduler from being re-entrant, which could potentially be difficult to debug later.

[catloop] Enhancement: Remove all calls to wait

---

src/rust/collections/concurrent_ring.rs
src/rust/collections/ring.rs
src/rust/inetstack/protocols/tcp/established/background/acknowledger.rs
src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs
src/rust/inetstack/protocols/tcp/established/background/sender.rs
src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
src/rust/lib.rs

This PR moves Demikernel closer to stable Rust, removing never_type, type_alias_impl_trait, and slice_ptr_get.

[demikernel] Enhacement: remove unstable features 

---

Cargo.toml

The windows build seems to be taking the newest version of socket2 available, so we need to bump the windows-sys crate to match.

[build] Enhancement: Bump socket2 version

---

src/rust/catloop/transport.rs
src/rust/catmem/mod.rs
src/rust/catnap/linux/transport.rs
src/rust/catnap/win/transport.rs
src/rust/demikernel/libos/memory.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network/libos.rs
src/rust/demikernel/libos/network/mod.rs
src/rust/inetstack/mod.rs
src/rust/runtime/mod.rs
src/rust/runtime/network/transport.rs

This PR closes #1173 by unifying the hierarchy of memory allocation for DemiBuffers. In the past, we were allocating Demibuffers out of the libOS and then freeing them through the shared runtime, which caused a memory leak because those were two different instances of the MemoryRuntime. Now, all DemiBuffer allocations go through the libOS first, then the transport and then the Network(Memory)Runtime. Since not all libOSes have NetworkRuntimes, some of the simply use the default heap allocator in the transport. However, we need to be careful in the future when supporting multiple libOSes with multiple transports to free DemiBuffers back to the right pool. In fact, we should probably have more tags to enable this.

[libos] Bug Fix: Unify DemiBuffer allocation

---

examples/rust/tcp-push-pop.rs

This PR fixes the `tcp-push-pop` example to abort server execution if client goes idle.
https://github.com/microsoft/demikernel/issues/1018

[examples] Abort Server on Idle Client

---

src/rust/catloop/socket.rs
src/rust/catloop/transport.rs
src/rust/catnap/linux/active_socket.rs
src/rust/catnap/linux/socket.rs
src/rust/catnap/linux/transport.rs
src/rust/catnap/win/transport.rs
src/rust/demikernel/libos/network/queue.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/udp/peer.rs
src/rust/runtime/network/transport.rs

When we added the transport trait we introduced a copy into almost all of the libOSes because the pop API took a DemiBuffer in and filled it. This removes those copies and lets the transport allocate the DemiBuffer and directly return it.

[libos] Remove copy from transport API

---

src/rust/runtime/mod.rs
src/rust/runtime/scheduler/task.rs

This PR updates `get_result` function to avoid a clone of result.

[scheduler] Enhancement: Update get_result function.

---

nettest/input/pop-blocking.pkt
src/rust/runtime/mod.rs
src/rust/runtime/timer.rs

This PR removes entries from the ordered heap in the global timer when a coroutine is no longer waiting on it. It also reduces the scope of the global variable that holds the timer since another PR will soon remove the global reference to the scheduler.

[runtime] Bug Fix: Clean up spurious wake ups in the timer

---

tests/rust/pipe-test/async_close/mod.rs

With our recent architectural changes from Yielders to condition variables, we no longer pass ECANCELED when a queue is closed but the operation fails with EBADF instead from the state machine.

[testing] Bug Fix: Change catmem errors to EBADF

---

examples/rust/pipe-ping-pong.rs
examples/rust/pipe-push-pop.rs
examples/rust/tcp-ping-pong.rs
examples/rust/tcp-push-pop.rs
examples/rust/udp-ping-pong.rs
examples/rust/udp-push-pop.rs
src/rust/catmem/mod.rs
src/rust/collections/concurrent_ring.rs
src/rust/collections/raw_array.rs
src/rust/collections/ring.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network/libos.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/udp/peer.rs
src/rust/lib.rs
src/rust/perftools/profiler/mod.rs
src/rust/runtime/mod.rs
src/rust/runtime/scheduler/group.rs
src/rust/runtime/scheduler/scheduler.rs
src/rust/runtime/scheduler/task.rs

This PR adds a feature to our profiler to measure the time spent in async blocks. It only supports fused (non-reentrant) blocks for now. It works by simply wrapping a Future around the existing code that measures when we enter the async block and stops the clock when we exit with either a Pending or Ready status. 
For now, I have annotated all of our coroutines but nothing more detailed. We should add more annotations, especially around the different async workers that all run in a single background coroutine.

[perf] Feature: Adding support for async profiling

---

linux.mk

Previously, we always compiled without the profiler feature flag through the Make file. Now if the feature flag is set to yes, then we will compile the profiler.

[compile] Bug Fix: Enable profiler compile

---

src/rust/perftools/profiler/mod.rs

Printing at the info level is too much for every time we enter and leave a scope. It is unclear if we even want trace level print outs since we enter and exit the polling coroutines frequently.

[perf] Bug Fix: Remove extraneous tracing

---

src/rust/pal/arch.rs
src/rust/runtime/memory/buffer_pool.rs
src/rust/runtime/memory/demibuffer.rs
src/rust/runtime/memory/memory_pool.rs
src/rust/runtime/memory/mod.rs

This PR adds two new structs: `MemoryPool` and `BufferPool`. `MemoryPool` is a pool of homogeneously-sized buffers. `BufferPool` wraps and imposes additional requirements on `MemoryPool` to be useful with `DemiBuffer`. Additionally, `DemiBuffer`s can not be created from pooled memory using `DemiBuffer::new_in_pool`.

[runtime] Enhancement: add BufferPool and MemoryPool types for pooling DemiBuffer allocation

---

.github/workflows/catloop.yml
.github/workflows/catmem.yml
.github/workflows/catnap.yml
.github/workflows/catnapw.yml
.github/workflows/catnip.yml
.github/workflows/catpowder.yml

This PR changes the triggering strategy for our CI.
Previously, we would trigger workflows on every push made to a matching branch. With changes introduced in this PR, workflow runs now trigger only when a PR is opened or updated.
- Workflow runs are now triggered only when opening or updating PRs
The motivation for this change is twofold:
- Enable access to PRs context API. This is required to leverage further automation CI (ie. post comments on PRs with performance numbers).
- Enable workflows to run on PRs made by external contributors (upon approval).

[ci] Run Workflows Only On PRs

---

examples/tcp-echo/main.rs
src/rust/catnap/linux/transport.rs
src/rust/demikernel/libos/name.rs
tools/ci/config/ci_map.yaml
tools/ci/job/linux.py
tools/demikernel_ci.py

This PR add support for multicore execution to our tcp-echo benchmark as an example of how we will handle basic multi-core architectures with RSS support. It currently only works with Catnap because there is more configuration that needs to be done for DPDK support. Since it has a share nothing architecture, it should work fine with Catloop and Catmem but is not currently supported.

[testing] Add multi-core support to TCP echo

---

src/rust/runtime/memory/demibuffer.rs

This PR fixes undefined behavior when a dereferencing zero length `demibuffer`.

[runtime] Avoid UB for Zero Length Buffer

---

tests/rust/tcp.rs

This PR fixes TCP unit tests to work on windows.
```pwsh
nmake DEBUG=yes RUST_LOG=none CONFIG_PATH=C:\config.yaml LIBOS=catnap test-unit-rust-tcp
```

[test] Windows Support for TCP Unit Tests

---

src/rust/runtime/memory/mod.rs

This PR introduces a check for disallowing zero-sized buffer allocation.

[ci] Don't Allocate Zero-Length Buffer

---

nettest/input/pop-blocking.pkt
nettest/input/pop-push-blocking.pkt
src/rust/inetstack/protocols/tcp/peer.rs

This PR fixes the TCP accept function to insert the connected peer in the TcpPeer::addresses and calculate the window scale.

[inetstack] Bug Fix: TCP accept and Window Scale

---

include/demi/cc.h
include/demi/libos.h
include/demi/sga.h
include/demi/types.h
include/demi/wait.h
src/rust/catmem/mod.rs
src/rust/demikernel/bindings.rs
src/rust/demikernel/libos/memory.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network/libos.rs
src/rust/demikernel/libos/network/mod.rs
src/rust/lib.rs
src/rust/runtime/mod.rs
tests/c/syscalls.c

This PR adds a new binding to get the next (n) completed operation(s). I also added some annotations to the bindings to engage some correctness checking on the behalf of GCC/clang/MSVC.

[runtime] Enhancement: add new demi_wait_next_n runtime binding

---

src/rust/runtime/mod.rs
tests/rust/tcp-test/connect/mod.rs
tests/rust/tcp-test/listen/mod.rs

Currently our timer resolution is 64 scheduler tasks. Assuming each task runs for roughly 100ns, we are checking the clock every 6.4us, which is too frequently to make a sys call. Thus, this PR increases the timer resolution to 1024, which is roughly once every 100us. This should reduce the sys call overhead, while still providing a reasonable timer granularity.

[runtime] Enhancement: Increase timer resolution

---

tests/rust/tcp-test/accept/mod.rs
tests/rust/tcp-test/wait/mod.rs

Move all of our error testing on integration tests to check_for_network_error. We introduced the function some time ago but there were still some lingering integration tests that did not use it.

[testing] Bug Fix: Add proper error checking

---

src/rust/collections/concurrent_ring.rs

This PR exposes and fixes an overflow bug that was happening when popping data from a concurrent ring buffer.

[collections] Overflow on Buffer Copy

---

src/rust/collections/concurrent_ring.rs

This PR fixes invalid push size for concurrent ringle buffers. It also adds more test units to this data structure.

[collections] Check for Invalid Push Size of Concurrent Ring Buffer

---

man/demi_init.md
src/rust/demikernel/bindings.rs

Multiple calls to demi_init would create a new libOS and the old one would leak. This change makes it so that a call to demi_init immediately returns if there is a libOS already initialized.

[demikernel] Bug Fix: Don't leak libos when calling init more than once

---

src/rust/catnap/linux/transport.rs

Currently, if the socket is set to non-blocking when created, set_nonblocking will return an error. Therefore, check if the socket is nonblocking before calling set_nonblocking.

[catnap] Bug Fix: Check if socket is already nonblocking

---

src/rust/runtime/timer.rs

Turn the timer unit tests back on now that we are not using a global scheduler any more

[testing] Turn timer tests back on

---

tests/rust/tcp.rs

We previously removed all raw data calls to Demikernel but this PR removes any references to old push2 interface. Closes #196

[testing] Remove references to push2

---

src/rust/catpowder/runtime/mod.rs
src/rust/catpowder/runtime/rawsocket/rawsocket.rs

Currently, we do not close the raw socket on exit, which possibly causes a lingering socket in Linux when we crash. Closes #671

[catpowder] Close Raw Socket

---

include/demi/libos.h
tests/c/syscalls.c

- This PR closes #73 
- This PR closes #74 
This PR introduces a C unit tests for `demi_getsockopt()` and `demi_setsockopt()`.
https://github.com/microsoft/demikernel/pull/1257

[pdpix] Expose System Calls for Setting / Getting Socket Options

---

man/demi_getsockopt.md
man/demi_setsockopt.md
src/rust/demikernel/bindings.rs
src/rust/demikernel/libos/network/queue.rs
src/rust/runtime/network/socket/state.rs

- This PR closes https://github.com/microsoft/demikernel/issues/1269
- This PR fixes standard error codes for `demi_setsockopt()` and `demi_getsockopt()`
- This PR introduces documentation for `demi_setsockopt()` and `demi_getsockopt()`

[libos] Disallow Setting SO_LINGER When Socket is Closing

---

include/demi/libos.h
man/demi_getpeername.md
shim/include/glue.h
shim/src/ctrl/getpeername.c
shim/src/glue.c
src/rust/catloop/socket.rs
src/rust/catloop/transport.rs
src/rust/catnap/linux/transport.rs
src/rust/catnap/win/socket.rs
src/rust/catnap/win/transport.rs
src/rust/catnap/win/winsock.rs
src/rust/demikernel/bindings.rs
src/rust/demikernel/libos/mod.rs
src/rust/demikernel/libos/network/libos.rs
src/rust/demikernel/libos/network/mod.rs
src/rust/demikernel/libos/network/queue.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/tcp/socket.rs
src/rust/pal/functions.rs
src/rust/runtime/network/transport.rs
tests/c/syscalls.c

Adding a getpeername call to the demikernel, so that we can interpose libc getpeername calls.

[pdpix] `getpeername()`

---

src/rust/runtime/mod.rs

Bing observed performance regression between Demikernel builds. The TIMER resolution changes that were introduced between the build were the root cause. So, tuning these values manually to work around this issue for now. Refer to attached files for more details.
[RCA.pdf](https://github.com/microsoft/demikernel/files/15339187/RCA.pdf)
[TestWorkaround.pdf](https://github.com/microsoft/demikernel/files/15339194/TestWorkaround.pdf)

[runtime] Workaround: Adjust TIMER resolutions to fix perf regression

---

src/rust/demikernel/libos/mod.rs

This PR removes an error where we lose the current scope in the profiler. Because all coroutines belong to the root scope, when we enter a coroutine while in another scope, that scope is not saved. Normally, any scope entered within a previous scope is rooted at the previous scope. However, this would create a confusing hierarchy for the coroutines where they all belong to what ever scope they were first scheduled in. Thus, we consider scopes that enter coroutines to be invalid for our profiler.

[libos] Bug Fix: Remove profiler scopes from coroutine polling functions

---

shim/include/glue.h
shim/src/ctrl/getpeername.c
shim/src/ctrl/getsockopt.c
shim/src/ctrl/setsockopt.c
shim/src/data/recv.c
shim/src/data/send.c
shim/src/glue.c
shim/src/interpose.c
shim/src/utils.h

This pull request deals with a couple of issues with the shim library
- Fixes race conditions when initializing the demikernel
- Makes sure every call to the demikernel is wrapped with the DEMI_CALL macro (there were a few calls that we forgot about and that were causing issues)
- Sets errno before returning an error from getpeername

[shim] Shim race conditions

---

nettest/input/connect/connect-refused.pkt
src/rust/inetstack/protocols/tcp/active_open.rs
src/rust/inetstack/protocols/tcp/peer.rs
src/rust/inetstack/protocols/tcp/socket.rs
tools/demikernel_ci.py

This PR closes #597. It also adds all integration tests for Catpowder and Catnip

[inetstack] Properly close connecting sockets

---

tools/ci/config/test/catnip.yaml
tools/ci/config/test/catpowder.yaml

This PR turns on more TCP echo tests. The goal of this PR is to align Catpowder and Catnip with the same set of tests that Catnap currently runs on our CI.

[testing] Enhancement: Turn on more inetstack tests

---

include/demi/libos.h

Fixes a missed header in the previous PR.

[include] Bug Fix: replace <winsock.h> with <WinSock2.h> in libos.h

---

.github/workflows/catnap.yml
.github/workflows/catnip.yml
.github/workflows/catpowder.yml

The merge on dev branch does not trigger the run for report-performance. This change enables that.

[ci] Enable perf report for dev branch

---

examples/tcp-echo/main.rs

Measure the end-to-end CPU cycles for the tcp-echo test.

[tcp-echo] Measure end-to-end CPU cycles

---

examples/pipe-open/main.rs
examples/rust/pipe-ping-pong.rs
examples/rust/pipe-push-pop.rs
examples/rust/tcp-dump.rs
examples/rust/tcp-ping-pong.rs
examples/rust/tcp-pktgen.rs
examples/rust/tcp-push-pop.rs
examples/rust/udp-dump.rs
examples/rust/udp-echo.rs
examples/rust/udp-ping-pong.rs
examples/rust/udp-pktgen.rs
examples/rust/udp-push-pop.rs
examples/rust/udp-relay.rs
examples/tcp-close/main.rs
examples/tcp-echo/main.rs
examples/tcp-wait/main.rs

The timer in main() functions never go off. This causes other unexpected issues as shown in the accompanying image.
Until we find a satisfactory solution, we will not do end-2-end measurement using the existing framework. I will send out an additional PR to add end-2-end measurements using rdtscp directly.

[examples] Revert timer in main

---

src/rust/runtime/scheduler/scheduler.rs

This PR fixes a leak in our scheduler that was causing the id map to grow continuously.

[runtime] Bug Fix: Remove task id leak in scheduler

---

shim/src/interpose.c

This PR fixes initialization issues of Demikernel in the POSIX SHIM layer.
Without this modification, initialization would be performed only when `epoll_create()` is the very first call performed by the application.

[shim] Missing Initialization on Many Calls

---

linux.mk

This PR fixes the build system to build the `LD_LIBRARY_PATH` to include the library directory.

[build] Missing Lib in LD_LIBRARY_PATH

---

shim/src/interpose.c

Incorrect parenthesis were causing the evaluation of conditional expression to be incorrect.

[shim] Fix evaluation of conditional expression in epoll_create

---

shim/src/interpose.c

This PR isolates some changes introduced by https://github.com/microsoft/demikernel/pull/1351.

[shim] Bad Initialization for `vfcntl()`, `epoll_ctl()`, `epoll_wait()` and `epoll_create()`

---

src/rust/catnip/runtime/mod.rs
src/rust/catpowder/linux/mod.rs
src/rust/catpowder/win/runtime.rs
src/rust/inetstack/protocols/arp/packet/message.rs
src/rust/inetstack/protocols/arp/peer.rs
src/rust/inetstack/protocols/arp/tests.rs
src/rust/inetstack/protocols/icmpv4/datagram/message.rs
src/rust/inetstack/protocols/icmpv4/peer.rs
src/rust/inetstack/protocols/tcp/active_open.rs
src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/inetstack/protocols/tcp/segment.rs
src/rust/inetstack/protocols/tcp/tests/simulator.rs
src/rust/inetstack/protocols/udp/datagram/mod.rs
src/rust/inetstack/protocols/udp/socket.rs
src/rust/inetstack/test_helpers/runtime.rs
src/rust/runtime/network/mod.rs
tests/rust/common/runtime.rs

This PR removes unnecessary clones in the inetstack.

[inetstack] Enhancement: Remove most clones

---

src/rust/catnip/runtime/mod.rs
src/rust/catpowder/linux/mod.rs
src/rust/catpowder/win/runtime.rs
src/rust/inetstack/mod.rs
src/rust/inetstack/protocols/arp/peer.rs
src/rust/inetstack/protocols/icmpv4/peer.rs
src/rust/inetstack/protocols/tcp/active_open.rs
src/rust/inetstack/protocols/tcp/established/ctrlblk.rs
src/rust/inetstack/protocols/tcp/passive_open.rs
src/rust/inetstack/protocols/udp/socket.rs
src/rust/inetstack/test_helpers/runtime.rs
src/rust/runtime/network/mod.rs
tests/rust/common/runtime.rs

This PR adds return values to the transmit and receive functions in the network runtime trait, so that we can remove panics and silent errors to return a value.

[runtime] Add return values to transmit and receive in the network runtime

---

src/rust/runtime/memory/demibuffer.rs

This PR implements a prepend function for both DPDK and heap allocated buffers. It allocates some headroom when allocating DemiBuffers so that we can use it later for packet headers.

[DemiBuffer] Implement prepend

---

examples/rust/tcp-ping-pong.rs
examples/rust/tcp-push-pop.rs
src/rust/inetstack/protocols/tcp/socket.rs

This PR replaces a wait for the ack to the push function in our inetstack. This was accidentally removed by me at some point. It close #1340

[inetstack] Bug Fix: Wait for ack
