README.md
Description
========
Updating README to link SOSP paper.
=> Update readme to point to SOSP paper

Cargo.toml, src/catnip/interop.rs, src/catnip/mod.rs, src/catpowder/interop.rs, src/catpowder/mod.rs, src/demikernel/bindings.rs
Description
========
This PR is a follow up of https://github.com/demikernel/catnip/pull/136.
Note that pointers to the network stack were update, as well as there is some re-architecting required in order to merge similar logic.
=> [demikernel] Moving In SGA System Calls

src/catnap/futures/accept.rs, src/catnap/futures/mod.rs, src/catnap/mod.rs
Description
========
This pull request fixes issue https://github.com/demikernel/demikernel/issues/58.
=> [catnap] Bad `OperationResult` for `accept()`

Makefile
Description
========
In this PR I fix issue https://github.com/demikernel/demikernel/issues/65.
=> [build] Malformed Paths When Multiple Locations Are Found

.github/workflows/catnap-tcp-pingpong.yml, .github/workflows/catnap-tcp-pushpop.yml, .github/workflows/catnap-udp-pingpong.yml, .github/workflows/catnap-udp-pushpop.yml, .github/workflows/catnip-tcp-pingpong.yml, .github/workflows/catnip-tcp-pushpop.yml, .github/workflows/catnip-udp-pingpong.yml, .github/workflows/catnip-udp-pushpop.yml, .github/workflows/catpowder-tcp-pingpong.yml, .github/workflows/catpowder-tcp-pushpop.yml, .github/workflows/catpowder-udp-pingpong.yml, .github/workflows/catpowder-udp-pushpop.yml, tests/pingpong.rs, tests/pushpop.rs
Description
========
In this PR I introduce the following features:
- https://github.com/demikernel/demikernel/issues/42
- https://github.com/demikernel/demikernel/issues/43
=> [test] System Testing for TCP

src/catnap/futures/accept.rs
Description
========
In this PR I fix the bug described in issue https://github.com/demikernel/demikernel/issues/89.
=> [catnap] Set Async Opts in New Socket

.github/workflows/build-libs.yml, .github/workflows/build-tests.yml, .github/workflows/catnap-tcp-pingpong.yml, .github/workflows/catnap-tcp-pushpop.yml, .github/workflows/catnap-udp-pingpong.yml, .github/workflows/catnap-udp-pushpop.yml, .github/workflows/catnap-unit-tests.yml
Description
========
In this PR I introduce the following enhancements:
- Update execution hosts for build workflows (03f911657f81ac139ad4d8cb739efb929dca05b7)
- Disable execution hosts for catnap workflows (1aeefb5d4ff601153d4509f66c3f3e75c23f591c)
=> [test] Updating Workflows

.github/workflows/catnap-tcp-pingpong.yml, .github/workflows/catnip-tcp-pingpong.yml, .github/workflows/catnip-unit-test.yml, .github/workflows/catpowder-tcp-pingpong.yml, .github/workflows/catpowder-unit-test.yml, src/catnap/futures/accept.rs, src/catnap/futures/connect.rs, src/catnap/futures/mod.rs, src/catnap/futures/pop.rs, src/catnap/futures/push.rs, src/catnap/futures/pushto.rs, tests/pingpong.rs
Description
========
In this PR, I introduce a system-level test that covers the issue https://github.com/demikernel/demikernel/issues/91.
Additionally in commit 327e0cde4f11539504ed647d794f9e95d1bf3002, I turn off traces on polling path, to ease debugging on Catnap LibOS.
=> [test] TCP Ping Pong with Multiple Accepts

README.md
Description
========
In this PR I update the README file.
Related Issues
==========
- https://github.com/demikernel/demikernel/issues/93
- https://github.com/demikernel/demikernel/issues/81
=> [doc] Updating README

include/dmtr/types.h
Description
========
This PR fixes issue https://github.com/demikernel/demikernel/issues/97.
=> [pdpix] Missing DMTR_OPC_FAILED

Cargo.toml
Description
========
In this PR I bump the version of the network stack.
=> [contrib] Updating Network Stack

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement-request.md, .github/ISSUE_TEMPLATE/feature-request.md
Description
========
In this PR I add templates for GitHub Issues.
=> [doc] Adding Templates for Issues

.github/workflows/catcollar-build.yml, .github/workflows/catcollar-tcp-pingpong.yml, .github/workflows/catcollar-tcp-pushpop.yml, .github/workflows/catcollar-udp-pingpong.yml, .github/workflows/catcollar-udp-pushpop.yml, .github/workflows/catcollar-unit-tests.yml, Cargo.toml, Makefile, src/catcollar/futures/accept.rs, src/catcollar/futures/connect.rs, src/catcollar/futures/mod.rs, src/catcollar/futures/pop.rs, src/catcollar/futures/push.rs, src/catcollar/futures/pushto.rs, src/catcollar/iouring.rs, src/catcollar/mod.rs, src/catcollar/runtime/memory.rs, src/catcollar/runtime/mod.rs, src/catcollar/runtime/network.rs, src/catcollar/runtime/scheduler.rs, src/catcollar/runtime/utils.rs, src/demikernel/libos.rs, src/lib.rs, tests/common/catcollar.rs, tests/common/mod.rs
Description
========
In this PR I introduce the initial implementation of Catcollar, our LibOS over [liburing](https://github.com/axboe/liburing).
=> [catcollar] Initial LibOS Implementation

Cargo.toml, src/catcollar/mod.rs, src/catnap/mod.rs, src/catnip/interop.rs, src/catnip/mod.rs, src/catnip/runtime/memory/manager.rs, src/catnip/runtime/network.rs, src/catpowder/interop.rs, src/catpowder/mod.rs, src/catpowder/runtime/network.rs, src/demikernel/bindings.rs, src/demikernel/libos.rs, src/lib.rs
Description
========
In this PR I bump the version of the `inetstack` crate.
=> [contrib] Bumping `inetstack`

Cargo.toml, src/catcollar/futures/mod.rs, src/catcollar/mod.rs, src/catcollar/runtime/mod.rs, src/catcollar/runtime/scheduler.rs, src/catnap/futures/mod.rs, src/catnap/mod.rs, src/catnap/runtime.rs, src/catnip/runtime/mod.rs, src/catnip/runtime/scheduler.rs, src/catpowder/runtime/mod.rs, src/catpowder/runtime/scheduler.rs, tests/c/syscalls.c
Description
========
In this PR I bump the inetstack, runtime and shceduler crates.
=> [contrib] Bump inetstack, runtime and scheduler

.github/workflows/catcollar-tcp-pingpong.yml, .github/workflows/catcollar-tcp-pushpop.yml, .github/workflows/catcollar-udp-pingpong.yml, .github/workflows/catcollar-udp-pushpop.yml, .gitignore, Cargo.toml, README.md
Description
========
In this PR I update the external dependencies of this repository.
The following dependencies were updated:
- `anyhow`
- `clap`
- `inetstack`
- `libc`
- `rand`
- `log`
- `socket2`
Related Issues
=========
The `nix` create was not updated due to issue #122.
=> [contrib] Updating External Dependencies

Cargo.toml
Description
-------------
This PR updates dependencies.
- Updated `anyhow` crate
=> [contrib] Updating Dependencies

tests/c/Makefile, tests/c/tcp-push-pop.c
Description
-------------
This PR is a partial fix for issue https://github.com/demikernel/demikernel/issues/131.
Summary Changes
----------------------
- Introduced `tcp-push-pop` test for C API.
Further Considerations
--------------------------
- The newly introduced test `tcp-push-pop` has not yet been integrated with our regression system.
=> [test] TCP Push Pop Test for C API

Makefile, README.md
Description
--------------
This PR fixes https://github.com/demikernel/demikernel/issues/100.
- Suppressed "File Not Found" warnings from build.
- Added prints to relevant environment in the build.
- Patched the documentation with notes on relevant environment variables.
=> [build] Suppress Warning Message When Building Catnap or Catpowder

tests/c/Makefile, tests/c/udp-ping-pong.c
Description
-------------
This PR is a partial fix for https://github.com/demikernel/demikernel/issues/131.
- Introduced C test for UDP ping pong
=> [test] UDP Ping Pong in C

src/rust/catcollar/runtime/memory.rs
Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/153.
- Fixed `alloc_sgarray()` to rely on the Buffer abstraction
- Fixed `free_sgarray()` to rely on the Buffer abstraction
=> [catcollar] Use Buffer Abstraction

src/rust/catnip/config.rs, src/rust/catnip/mod.rs, src/rust/catpowder/config.rs, src/rust/catpowder/mod.rs, src/rust/demikernel/config.rs, tests/rust/common/catcollar.rs, tests/rust/common/catnap.rs, tests/rust/common/catnip.rs, tests/rust/common/catpowder.rs, tests/rust/common/config.rs, tests/rust/pingpong.rs, tests/rust/pushpop.rs
Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/50.
- Moved specific config parameters to each libos module.
=> [pdpix] Generic Config Parsing

.github/workflows/catcollar.yml, .github/workflows/catnap.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml, Cargo.toml, examples/rust/tcp-ping-pong.rs, examples/rust/tcp-push-pop.rs, examples/rust/udp-ping-pong.rs, examples/rust/udp-push-pop.rs, src/rust/catcollar/futures/mod.rs, src/rust/catcollar/mod.rs, src/rust/catcollar/runtime/memory.rs, src/rust/catnap/futures/mod.rs, src/rust/catnap/mod.rs, src/rust/catnap/runtime.rs, src/rust/catpowder/runtime/memory.rs, src/rust/demikernel/bindings.rs, src/rust/demikernel/libos.rs, src/rust/demikernel/libos/mod.rs, src/rust/demikernel/libos/name.rs, src/rust/demikernel/libos/network.rs, src/rust/lib.rs, tests/rust/sga.rs
Description
--------------
This PR is a partial fix for https://github.com/demikernel/demikernel/issues/158.
- Enabled LibOS instantiation to fail rather than panicking.
- Enabled build composition of different flavors of LibOSes.
- Build features `catnap-libos`, `catnip-libos`, `catpowder-libos` and `catcollar-libos` are no longer mutually exclusive.
- Enabled dynamic LibOS flavor selection using environment variables.
=> [pdpix] Build Composition of LibOSes

man/demi_accept.md, man/demi_bind.md, man/demi_init.md, man/demi_listen.md, man/demi_push.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_push()` system call.
=> [doc] `demi_push()` Manual Page

man/demi_accept.md, man/demi_bind.md, man/demi_close.md, man/demi_connect.md, man/demi_init.md, man/demi_listen.md, man/demi_pop.md, man/demi_push.md, man/demi_pushto.md, man/demi_sgaalloc.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_sgaalloc()` system call.
=> [doc] `demi_sgaalloc()` Manual Page

man/demi_accept.md, man/demi_bind.md, man/demi_close.md, man/demi_connect.md, man/demi_init.md, man/demi_listen.md, man/demi_pop.md, man/demi_push.md, man/demi_pushto.md, man/demi_sgaalloc.md, man/demi_sgafree.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_sgafree()` system call.
=> [doc] `demi_sgafree()` Manual Page

man/demi_accept.md, man/demi_bind.md, man/demi_close.md, man/demi_connect.md, man/demi_init.md, man/demi_listen.md, man/demi_pop.md, man/demi_push.md, man/demi_pushto.md, man/demi_sgaalloc.md, man/demi_sgafree.md, man/demi_socket.md, man/demi_wait.md
Description
-------------
- Added manual page for `demi_wait()` system call.
- Added manual page for `demi_wait_any()` system call.
=> [doc] `demi_wait()` Manual Page

man/demi_socket.md
Description
-------------
- Added manual page for `demi_socket()` system call.
=> [doc] `demi_socket()` Manual Page

man/demi_init.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_init()` system call.
=> [doc] `demi_init()` Manual Page

man/demi_init.md, man/demi_listen.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_listen()` system call.
=> [doc] `demi_listen()` Manual Page

man/demi_bind.md, man/demi_init.md, man/demi_listen.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_bind()` system call.
=> [doc] `demi_bind()` Manual Page

man/demi_accept.md, man/demi_bind.md, man/demi_init.md, man/demi_listen.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_accept()` system call.
=> [doc] `demi_accept()` Manual Page

man/demi_accept.md, man/demi_bind.md, man/demi_init.md, man/demi_listen.md, man/demi_push.md, man/demi_pushto.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_pushto()` system call.
=> [doc] `demi_pushto()` Manual Page

man/demi_accept.md, man/demi_bind.md, man/demi_init.md, man/demi_listen.md, man/demi_pop.md, man/demi_push.md, man/demi_pushto.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_pop()` system call.
=> [doc] `demi_pop()` Manual Page

man/demi_accept.md, man/demi_bind.md, man/demi_connect.md, man/demi_init.md, man/demi_listen.md, man/demi_pop.md, man/demi_push.md, man/demi_pushto.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_connect()` system call.
=> [doc] `demi_connect()` Manual Page

man/demi_accept.md, man/demi_bind.md, man/demi_close.md, man/demi_connect.md, man/demi_init.md, man/demi_listen.md, man/demi_pop.md, man/demi_push.md, man/demi_pushto.md, man/demi_socket.md
Description
-------------
- Added manual page for `demi_close()` system call.
=> [doc] `demi_close()` Manual Page

src/rust/collections/mod.rs, src/rust/collections/ring.rs, src/rust/lib.rs
Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/287.
- Introduced `RingBuffer` abstraction
=> [collections] Ring Buffer Abstraction

src/rust/collections/mod.rs, src/rust/collections/ring.rs, src/rust/collections/shared_ring.rs, src/rust/pal/linux/shm.rs
Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/290.
- Introduced `SharedRingBuffer` abstraction.
=> [collections] Shared Ring Buffer Abstraction

src/rust/runtime/queue/mod.rs
Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/292.
- Added offsetting logic to identifiers of I/O queue descriptors.
=> [runtime] Offset Identifiers of I/O Queue Descriptors

src/rust/catcollar/mod.rs, src/rust/catnap/mod.rs, src/rust/demikernel/libos/mod.rs, src/rust/demikernel/libos/network.rs
Description
-------------
This PR is a workaround for https://github.com/demikernel/demikernel/issues/295.
- Renamed I/O queue descriptor variables
- Added annotations for deprecated system calls
- Fixed by socket type in Catcollar and Catnap
=> [pdpix] Tagging Deprecated System Calls

examples/rust/tcp-dump.rs, examples/rust/tcp-echo.rs, examples/rust/tcp-ping-pong.rs, examples/rust/tcp-pktgen.rs, examples/rust/tcp-push-pop.rs, examples/rust/udp-dump.rs, examples/rust/udp-echo.rs, examples/rust/udp-ping-pong.rs, examples/rust/udp-pktgen.rs, examples/rust/udp-push-pop.rs, examples/rust/udp-relay.rs
Description
-------------
This PR is related to https://github.com/demikernel/demikernel/issues/295.
- Rewrote all Rust examples to rely on PDPIX wait API.
=> [examples] Use PDPIX In Rust Examples

src/rust/catcollar/mod.rs, src/rust/catnap/mod.rs, src/rust/catnip/mod.rs, src/rust/catpowder/mod.rs, src/rust/demikernel/libos/network.rs
Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/306.
- Exposed required interface to PDPIX layer in order to build a generic `wait()` function
- Introduced a generic `wait()` function
=> [pdpix] Generic `wait()`

Cargo.toml, examples/c/common.c, examples/c/common.h, examples/c/linux.mk, examples/c/tcp-ping-pong.c, examples/c/tcp-push-pop.c, examples/c/udp-ping-pong.c, examples/c/udp-push-pop.c, examples/c/windows.mk, examples/rust/udp-echo.rs, include/demi/libos.h, include/demi/types.h, src/rust/catnapw/futures/accept.rs, src/rust/catnapw/futures/connect.rs, src/rust/catnapw/futures/mod.rs, src/rust/catnapw/futures/pop.rs, src/rust/catnapw/futures/push.rs, src/rust/catnapw/futures/pushto.rs, src/rust/catnapw/mod.rs, src/rust/catnapw/runtime.rs, src/rust/collections/mod.rs, src/rust/demikernel/bindings.rs, src/rust/demikernel/libos/mod.rs, src/rust/demikernel/libos/name.rs, src/rust/demikernel/libos/network.rs, src/rust/lib.rs, src/rust/pal/data_structures.rs, tests/c/syscalls.c, windows.mk
This is one of the PRs that addresses the issue https://github.com/demikernel/demikernel/issues/274.
Here are previous PRs for reference that created way for this change:
- https://github.com/demikernel/demikernel/pull/309
- https://github.com/demikernel/demikernel/pull/305
=> [winport] Enhancement: Add CatnapW for Windows

src/rust/catnip/runtime/mod.rs
Description
--------------
This PR fixes https://github.com/demikernel/demikernel/issues/330.
- Added some missing types to the source file.
- Moved MTU initialziation to end of port initialization routine.
=> [catnip] Wrong MTU Initialization

examples/rust/tcp-echo.rs
Description
-------------
This is a fix for https://github.com/demikernel/demikernel/issues/337.
- Changed `tcp-echo` to support multiple connections.
=> [examples] Support Multiple Clients in `tcp-echo`

examples/rust/tcp-dump.rs, examples/rust/tcp-echo.rs
Description
-------------
This is a partial fix for https://github.com/demikernel/demikernel/issues/337.
- Added missing type annotation to `tcp-echo`.
- Added multi-client support to `tcp-dump`
=> [examples] Multi-Client Support for `tcp-dump`

.github/workflows/catnap.yml
Description
-------------
In this PR I update the workflow file for Catnap to match the configuration of our testing infrastructure.
=> [ci] Updating Catnap Workflow

.github/workflows/catpowder.yml
Description
-------------
In this PR I update the workflow file for Catpowder to match the configuration of our testing infrastructure.
=> [ci] Updating Catpowder Workflow

.github/workflows/catcollar.yml
Description
-------------
In this PR I update the workflow file for Catcollar to match the configuration of our testing infrastructure.
=> [ci] Updating Catcollar Workflow

.github/workflows/cleanup.yml, .github/workflows/setup.yml
Description
-------------
This PR fixes the checkout commands that we have in our CI.
Since `dev` is now the main branch, we should be checking out on setup and clean up steps to it.
=> [ci] Checkout to Dev Branch

README.md, doc/testing.md, man/demi_wait.md
Description
-------------
This PR addresses [#356 ](https://github.com/demikernel/demikernel/issues/356)
- Added a new document that provides detailed instructions on how to test Demikernel
- Changed Demikernel's `README.md` file to link new testing document.
- Added missing entry to `demi_timedwait()` in the manual pages.
=> [doc] Testing Instructions

linux.mk, windows.mk
Description
-------------
This PR fixes https://github.com/demikernel/demikernel/issues/372.
- Re-enabled unit tests that we were skipping
- Fixed default system test
=> [test] Missing to Run Some Unit Tests in `test-unit-rust` Target

doc/testing.md, tools/demikernel-ci.py
Description
-------------
- This issue fixes https://github.com/demikernel/demikernel/issues/379.
- This issue fixes https://github.com/demikernel/demikernel/issues/380.
- This issue fixes https://github.com/demikernel/demikernel/issues/381.
- This issue fixes https://github.com/demikernel/demikernel/issues/382.
- Fixed the concerned issues.
- Changed the `testing.md` documentation accordingly.
=> [tools] Several Improvements for `demikernel-ci`

doc/testing.md
- Fixed minor typos on testing instructions
=> [doc] Fixing Minor Typos on Testing Instructions

examples/rust/tcp-ping-pong.rs, include/demi/libos.h, src/rust/demikernel/libos/network.rs
This PR fixes https://github.com/demikernel/demikernel/issues/390.
- Fixed `tcp-ping-pong` to buffer received response on client-side
- Changed `tcp-ping-pong` to send buffers with different payload at each round.
=> [test] `tcp-ping-pong` Does Not Wait for Full Receive Buffer

examples/rust/tcp-dump.rs, src/rust/catcollar/futures/pop.rs, src/rust/collections/ring.rs, src/rust/collections/shared_ring.rs, src/rust/lib.rs, src/rust/perftools/profiler/mod.rs, tests/rust/udp.rs
- Fixed some bug warnings
- Drop some unrequired `allow()` statements
=> [build] Fixing Build Warnings

tools/demikernel-ci.py
This PR fixes https://github.com/demikernel/demikernel/issues/395.
- Added support for overriding default `CONFIG_PATH` on run steps.
=> [ci] Enhancement: Support Config Path Override

tools/demikernel-ci.py
This PR closes https://github.com/demikernel/demikernel/issues/397
- Added an optional flag in `demikernel-ci` to run build steps only on one machine.
=> [tools] Support NFS Directories in `demikernel-ci`

tools/demikernel-ci.py
This PR closes https://github.com/demikernel/demikernel/issues/410
- Added missing initialization for `passed` variable in `wait_and_report()`
- Fixed test for number of executed jobs in `wait_and_report()`
=> [tools] Bad Check on Number of Executed Jobs in `demikernel-ci`

tools/demikernel-ci.py
- This PR fixes https://github.com/demikernel/demikernel/issues/416
- This PR fixes https://github.com/demikernel/demikernel/issues/404
- Added missing support for detached branches.
- Added type conversion for delay parameter.
- Fixed type annotations for `str` types.
- Fixed cleanup step to use `sudo` when required.
=> [tools] Minor Bug Fixes in `demikernel-ci`

src/rust/inetstack/protocols/icmpv4/peer.rs
This commit fixes https://github.com/demikernel/demikernel/issues/218
- Handled cancellation for ping requests.
- Added missing type annotations.
=> [inetstack] Handle Cancellation of Ping Requests

Cargo.toml, src/rust/catcollar/futures/accept.rs, src/rust/catcollar/futures/connect.rs, src/rust/catcollar/iouring.rs, src/rust/catcollar/mod.rs, src/rust/catcollar/runtime/mod.rs, src/rust/catnap/futures/accept.rs, src/rust/catnap/futures/connect.rs, src/rust/catnap/futures/pop.rs, src/rust/catnap/futures/push.rs, src/rust/catnap/futures/pushto.rs, src/rust/catnap/mod.rs, src/rust/catpowder/runtime/rawsocket/rawsocket.rs, src/rust/pal/linux/mod.rs
This PR closes https://github.com/demikernel/demikernel/issues/402.
- Dropped dependency on `nix` crate for Catnap LibOS.
- Dropped dependency on `nix` crate for Catcollar LibOS.
=> [build] Dropping Dependency on `nix`

src/rust/catcollar/futures/pop.rs, src/rust/catcollar/futures/push.rs, src/rust/catcollar/futures/pushto.rs, src/rust/catcollar/iouring.rs, src/rust/catcollar/mod.rs, src/rust/catcollar/runtime/mod.rs
This PR fixes https://github.com/demikernel/demikernel/issues/432
- Fixed memory leak for `iovec` structure in `msghdr` - we were not retrieving the correct heap-allocated pointer.
- Fixed logic for handling ongoing async operations - before https://github.com/demikernel/demikernel/pull/419 the socket was operating on sync mode.
=> [catcollar] Bad Logic for Async Ongoing Operations

Cargo.toml, examples/rust/udp-echo.rs, src/rust/catnapw/mod.rs, src/rust/demikernel/bindings.rs, src/rust/inetstack/mod.rs, src/rust/pal/constants.rs
Addresses issue: https://github.com/demikernel/demikernel/issues/417
=> [winport] Update the Windows crate 0.44.0

src/rust/catnapw/futures/accept.rs, src/rust/catnapw/futures/mod.rs, src/rust/catnapw/mod.rs
This commit fixes https://github.com/demikernel/demikernel/issues/364
=> [catnapw] Set Remote Address in Accept

.github/workflows/catloop.yml, .github/workflows/catmem.yml
This PR introduces support in GitHub actions for Catloop LibOS
=> [test] GitHub Actions Support for Catloop LibOS

.github/workflows/ssh-setup.yml, tools/demikernel_ci.py
This PR is a related to https://github.com/demikernel/demikernel/issues/456.
- Fixed Catloop LibOS pipeline in `demikernel_ci` to skip UDP tests
- Added Setup SSH action for workflows
=> [ci] Skip UDP Tests in `demikernel_ci` for Catloop LibOS

src/rust/lib.rs
This is related to https://github.com/demikernel/demikernel/issues/172
- Dropped unused features.
=> [build] Dropping Unused Features

src/rust/catloop/futures/mod.rs
- This commit fixes https://github.com/demikernel/demikernel/issues/465
=> [catloop] Bad Operation Result for Accept

src/rust/catnip/interop.rs
Partially addresses issue: https://github.com/demikernel/demikernel/issues/274.
=> [catnip] Adjust interop for PAL

tools/demikernel_ci.py
This PR closes https://github.com/demikernel/demikernel/issues/471.
- Added `output-dir` optional parameter to `demikernel_ci` to enable one to save logs in a custom directory.
=> [tools] Support Custom Output Directory in `demikernel_ci`

.github/workflows/catcollar.yml, .github/workflows/catloop.yml, .github/workflows/catnap.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml, tools/demikernel_ci.py
This PR closes https://github.com/demikernel/demikernel/issues/472
- Added a a parameter to `--test-system` option to enable one to specify a specific test system to run.
- Fixed regression system accordingly.
=> [tools] Run Individual System Tests in `demikernel_ci`

examples/c/windows.mk, windows.mk
Partially addresses issue: https://github.com/demikernel/demikernel/issues/274 (Support for Bing protoype)
=> [build] Enhancement: Enable dll/lib/pdb files for Bing prototyping effort

linux.mk
This commit closes https://github.com/demikernel/demikernel/issues/481
- https://github.com/demikernel/demikernel/issues/403
=> [build] Make `RUST_LOG` Overridable

src/rust/catcollar/mod.rs, src/rust/catnap/mod.rs
In this PR I dropped some functions that were marked as deprecated.
=> [build Dropping Deprecated Functions

scripts/setup/debian.sh, scripts/setup/dpdk.sh
This PR closes https://github.com/demikernel/demikernel/issues/463
=> [script] Missing Build Dependency for DPDK

.github/workflows/catmem.yml
This PR is a partial fix for https://github.com/demikernel/demikernel/issues/456
- Fixed regression pipeline for Catmem LibOS to leverage `demikernel-ci`
=> [ci] Leverage `demikernel_ci` for Catmem LibOS

src/rust/catcollar/mod.rs
This fixes issue #493. I realized that catcollar does not remove the queue descriptor from the sockets table or free it from the IoQueueTable.
=> [catcollar] Correctly Dree Data Structures on `close()`

.github/workflows/catpowder.yml, tools/demikernel_ci.py
This PR fixes the regression pipeline for Catpowder LibOS.
- Fixed workflow file to run regression pipeline for Catpowder instead of Catnap.
- Disable debug pipeline for Catpowder.
=> [ci] Fixing Regression Pipeline for Catpowder

src/rust/catloop/mod.rs
This PR fixes https://github.com/demikernel/demikernel/issues/497
- Added extra check for whether the bind address is already in use.
- Fixed error value when trying to bind a bound socket to a different address from `EBADF` to `EINVAL`.
This PR takes dependency on https://github.com/demikernel/demikernel/pull/513
=> [catloop] Do not Allow Multiple `bind()` to Same Address

tests/rust/tcp.rs, tools/demikernel_ci.py
This commit closes https://github.com/demikernel/demikernel/issues/519
- Added support in `demikernel-ci` to run `tcp-bind`.
- Dropped `tcp_bad_bind()` test.
=> [tests] Drop `tcp_bad_bind()` in Favor of `tcp-bind`

src/rust/inetstack/protocols/arp/peer.rs
This PR fixes https://github.com/demikernel/demikernel/issues/242
- Added a list of waiters to the ARP module to enable multiple waiters to wait on an ARP resolution.
=> [inetstack] Multiple Waiters for Address Resolution

src/rust/catnap/futures/close.rs, src/rust/catnap/futures/mod.rs, src/rust/catnap/mod.rs, src/rust/demikernel/libos/network.rs
This PR implements support for asynchronous close functionality in catnap.
=> [catnap] Implement async_close support

src/rust/catnip/interop.rs, src/rust/demikernel/libos/network.rs
This PR puts in the plumbing for supporting async_close in catnip.
=> [catnip] Implement async_close

src/rust/catpowder/interop.rs, src/rust/demikernel/libos/network.rs
This PR implements the plumbing for async_close in catpowder
=> [catpowder] Implement async_close

src/rust/catcollar/futures/close.rs, src/rust/catcollar/futures/mod.rs, src/rust/catcollar/mod.rs, src/rust/demikernel/libos/network.rs
This PR implements async_close for catcollar. It is almost identical in code to catnap.
=> [catcollar] Implement async_close

include/demi/types.h, src/rust/catcollar/mod.rs, src/rust/catloop/mod.rs, src/rust/catmem/mod.rs, src/rust/catnap/mod.rs, src/rust/catnip/interop.rs, src/rust/catpowder/interop.rs, src/rust/runtime/types/ops.rs
This PR fixes https://github.com/demikernel/demikernel/issues/525
=> [pdpix] Error Information in `demi_qresult_t`

tools/demikernel_ci.py
This PR enables `tcp-accept` in regressions.
=> [ci] Enable `tcp-accept` in Regressions

tools/demikernel_ci.py
This PR address support for test alias, so that future tests that support multiple run modes may be correctly reported.
=> [ci]  Support Test Alias

src/rust/catmem/futures/pop.rs
=> [catmem] Fix incorrect size comparison

src/rust/catmem/mod.rs
This commit fixes https://github.com/demikernel/demikernel/issues/565
=> [catmem] Invalid Queue Descriptor in Pop

tests/rust/tcp-test/close/async_close.rs, tests/rust/tcp-test/close/mod.rs
=> [test] Add tests for async_close

tests/rust/tcp-test/accept/mod.rs
This PR closes https://github.com/demikernel/demikernel/issues/549
Added the following integration tests for TCP `accept()`:
- Attempt to accept connections on a TCP socket that is closed.
=> [test] Integration Tests for TCP `accept()`

tests/rust/tcp-test/connect/mod.rs
This PR closes https://github.com/demikernel/demikernel/issues/554
Added the following integration tests for TCP `connect()`:
- Attempt to connect a TCP socket to a remote that is not accepting connections.
- Attempt to connect a TCP socket that is bound.
- Attempt to connect a TCP socket that is closed.
=> [test] Integration Tests for TCP `connect()`

examples/tcp-echo/client.rs, examples/tcp-echo/main.rs, tools/demikernel_ci.py
This PR closes https://github.com/demikernel/demikernel/issues/580
=> [examples] Concurrent Mode for `tcp-echo`

src/rust/catloop/mod.rs, src/rust/catnip/runtime/memory/manager.rs, src/rust/catnip/runtime/network.rs, src/rust/catpowder/runtime/network.rs, src/rust/inetstack/protocols/tcp/established/background/retransmitter.rs, src/rust/inetstack/protocols/tcp/established/background/sender.rs, src/rust/inetstack/protocols/tcp/established/congestion_control/cubic.rs, src/rust/inetstack/protocols/tcp/established/ctrlblk.rs, src/rust/inetstack/protocols/tcp/established/rto.rs, src/rust/inetstack/protocols/tcp/established/sender.rs, src/rust/inetstack/protocols/tcp/tests/mod.rs, src/rust/runtime/memory/demibuffer.rs, src/rust/runtime/memory/mod.rs, src/rust/runtime/types/memory.rs
This PR rewords TODOs in our source tree, so that they may all be trackable by the "Todo Tree" plugging in VS Code.
=> [doc] Reword TODOs in Source Tree

examples/pipe-open/server.rs, src/rust/catmem/mod.rs
- This PR closes https://github.com/demikernel/demikernel/issues/590
- Fixed `Catmem::pop()` to spawn a failed co-routine when the connection is reset (we were returned an error before)
- Fixed `Catmem::push()` to spawn a failed co-routine when the connection is reset (we were returned an error before)
- Improved some error messages in Catmem to print information about the failure context.
- Fixed `pipe-open` program to handle connection reset.
=> [catmem] Connection Reset in Push and Pop

examples/rust/tcp-ping-pong.rs
This PR closes #394. Currently we fill the packet with a single value. This change updates the fill to start with the iteration of the test and then fills the remainder of the packet with numerically increasing values.
=> [test] Add sanity check to payload order

tools/demikernel_ci.py
=> [test] Add .txt suffix to log files

examples/pipe-open/client.rs, examples/pipe-open/server.rs
This PR removes panic from examples/pipe-open and adds a reference to a new issue for fixing the error handling clean up of pipes.
=> [test] Remove panics from pipe-open system test

examples/tcp-close/client.rs, examples/tcp-close/server.rs
This PR removes the use of panic from the tests in examples/tcp-close. It also links a new issue created for cleaning up open sockets on error.
=> [test] Remove panics from tcp-close system test

examples/rust/pipe-ping-pong.rs, examples/rust/pipe-push-pop.rs
This PR removes all panics (and expects and unwraps) from the tests in examples/rust/pipe-*. I added links to a new issue for cleaning up open pipes and freeing scatter-gather arrays and linked it from the changes.
=> [test] Remove panic from pipe system tests

examples/rust/tcp-dump.rs, examples/rust/tcp-ping-pong.rs, examples/rust/tcp-pktgen.rs, examples/rust/tcp-push-pop.rs
This PR removes panics (and expects and unwraps) from the tcp system tests in examples/rust/tcp-*. It also links a new issue for cleaning up state on errors.
=> [test] Remove panic from TCP system tests

tests/rust/tcp-test/close/wait.rs
=> [test] wait(): Add TCP tests around wait()/close()

examples/tcp-close/args.rs, examples/tcp-close/client.rs, examples/tcp-close/main.rs, examples/tcp-close/server.rs
=> [tcp-close] Add `async_close()` support

src/rust/inetstack/collections/hashttlcache/tests.rs, src/rust/inetstack/protocols/arp/cache/tests.rs, src/rust/inetstack/protocols/arp/tests.rs, src/rust/inetstack/protocols/icmpv4/tests.rs, src/rust/inetstack/protocols/ipv4/tests.rs, src/rust/inetstack/protocols/tcp/sequence_number.rs, src/rust/inetstack/protocols/tcp/tests/established.rs, src/rust/inetstack/protocols/tcp/tests/setup.rs, src/rust/inetstack/protocols/udp/datagram/header.rs, src/rust/inetstack/protocols/udp/datagram/mod.rs, src/rust/inetstack/protocols/udp/tests.rs
This PR removes all panics, unwraps and asserts from the inetstack unit tests.
=> [test] Remove panic from inetstack unit tests

tests/rust/pipe-test/close/mod.rs, tests/rust/pipe-test/main.rs
This PR closes https://github.com/demikernel/demikernel/issues/617
=> [test] Integration Tests for Pipe `close`

src/rust/scheduler/page/page.rs, src/rust/scheduler/page/page_ref.rs, src/rust/scheduler/page/waker_ref.rs, src/rust/scheduler/pin_slab.rs, src/rust/scheduler/scheduler.rs
This PR removes panics, asserts, expects and unwraps from the scheduler unit tests.
=> [test] Remove panic from scheduler unit test

tests/rust/pipe-test/async_close/mod.rs, tests/rust/pipe-test/main.rs
This PR closes https://github.com/demikernel/demikernel/issues/620
=> [test] Integration Tests for Pipe `async_close()`

src/rust/catmem/mod.rs
This PR closes https://github.com/demikernel/demikernel/issues/591
=> [catmem] Don't Check for EoF on Push

tests/rust/pipe-test/args.rs, tests/rust/pipe-test/main.rs, tests/rust/pipe-test/push_wait/client.rs, tests/rust/pipe-test/push_wait/mod.rs, tests/rust/pipe-test/push_wait/server.rs
This PR partially addresses https://github.com/demikernel/demikernel/issues/619
I intentionally will submit one PR for each of the test cases, because they are more complex than usual integration tests.
- Added support for multiple running modes in `pipe-test`
- Added an integration test for "Attempt to wait for a push() operation to complete after closing a pipe".
=> [test] Wait Push After Closing Pipe

tools/demikernel_ci.py
This PR closes https://github.com/demikernel/demikernel/issues/675
=> [test] Enable `PROFILER` Flag in `demikernel_ci`

src/rust/catmem/mod.rs
This PR closes https://github.com/demikernel/demikernel/issues/684
- Removed infinite loop around `push_eof()`
- Changed `close()` to release queue descriptor even if `push_eof()` fails.
=> [catmem] Don't Push EoF Indefinitely

tests/rust/pipe-test/args.rs, tests/rust/pipe-test/main.rs, tests/rust/pipe-test/pop_wait/client.rs, tests/rust/pipe-test/pop_wait/mod.rs, tests/rust/pipe-test/pop_wait/server.rs
This commit partially addresses https://github.com/demikernel/demikernel/issues/619
- https://github.com/demikernel/demikernel/issues/684
- https://github.com/demikernel/demikernel/issues/521
- https://github.com/demikernel/demikernel/issues/552
=> [test] Wait Pop After Closing Pipe

tests/rust/pipe-test/create_pipe/mod.rs
This PR adds a test for intentionally leaving a pipe open after the LibOS goes out of scope. We use the same name to try to open the pipe again. Assuming that the LibOS correctly cleans up resources on exit, this test should be able to create another pipe with the same name.
=> [test] Add test for Catmem LibOS cleanup

tests/rust/tcp-test/close/async_close.rs
=> [test] Add more async_close() tests

examples/rust/linux.mk, examples/tcp-wait/args.rs, examples/tcp-wait/client.rs, examples/tcp-wait/main.rs, examples/tcp-wait/server.rs, tools/demikernel_ci.py
=> [test] Add tcp_wait utility

examples/tcp-echo/client.rs, examples/tcp-echo/server.rs
This PR adds additional clean up code to a drop function in the client and server for the tcp-echo application.  It closes #642
=> [test] Add drop function to tcp echo

examples/tcp-close/client.rs, examples/tcp-close/server.rs
This change registers all of the open sockets in the tcp-close tests and cleans them up in a drop function. It closes #640
=> [test] Add drop function to tcp-close

examples/rust/pipe-ping-pong.rs, examples/rust/pipe-push-pop.rs
These tests do not use data structures, so I could not use the drop function. Instead, I manually added close and free for each allocated socket and scatter-gather array. At some point, we should probably move this test to a client and server struct to be more similar to our other tests, but it would require some file restructuring as well. This PR closes #647
=> [test] Add cleanup code to pipe system tests

examples/rust/udp-dump.rs, examples/rust/udp-echo.rs, examples/rust/udp-ping-pong.rs, examples/rust/udp-pktgen.rs, examples/rust/udp-push-pop.rs, examples/rust/udp-relay.rs
This PR closes #651. For the tests with Application structs, I have added a drop function. For the other tests, I manually added close and freesga calls to explicitly clean up outside resources.
=> [test] Add cleanup to UDP system tests

src/rust/lib.rs, src/rust/runtime/mod.rs, src/rust/runtime/queue/mod.rs, src/rust/runtime/queue/operation_result.rs
=> [runtime] Remove QResult

src/rust/catnap/mod.rs, src/rust/catnap/socket.rs
This PR closes https://github.com/demikernel/demikernel/issues/625.
=> [runtime] Closing State for Sockets

src/rust/catnap/mod.rs
This PR closes https://github.com/demikernel/demikernel/issues/729.
- Added missing transition for connected state.
=> [catnap] Transition to Connected State

src/rust/demikernel/libos/mod.rs, tests/rust/sga.rs
This PR is a partial fix for https://github.com/demikernel/demikernel/issues/521
=> [bugfix] Poll in Every PDPIX Call

examples/rust/tcp-ping-pong.rs
=> [tcp-ping-pong] Refactor to add Drop

examples/rust/udp-ping-pong.rs
=> [udp-ping-pong] Refactor to add Drop

examples/rust/tcp-push-pop.rs
=> [tcp-push-pop] Refactor to add Drop

examples/rust/udp-push-pop.rs
=> [udp-push-pop] Refactor to add Drop

tools/demikernel_ci.py
This PR closes https://github.com/demikernel/demikernel/issues/748
=> [test] Don't Run Unit Tests Concurrently

examples/tcp-wait/client.rs, tools/demikernel_ci.py
This PR closes https://github.com/demikernel/demikernel/issues/521.
- Enabled all testing scenarios for `tcp-wait`.
- Added extra assertations to `pop` scenarios.
=> [test] Enabling Testing Scenarios for TCP Wait

examples/rust/pipe-push-pop.rs
=> [pipe-push-pop] Refactor to add Drop

src/rust/scheduler/handle.rs, src/rust/scheduler/scheduler.rs
This PR fixes some issues introduced in PR #722. Specifically it closes #750 and closes #752. It also cleans up some comments in the TaskHandle and adds some printouts.
=> [runtime] Fix Scheduler Issues

src/rust/catloop/futures/accept.rs, src/rust/catloop/futures/connect.rs
This PR closes https://github.com/demikernel/demikernel/issues/768
=> [catloop] Leaking Tasks on Connection Establishment Protocol

examples/tcp-close/server.rs
This PR closes https://github.com/demikernel/demikernel/issues/760
=> [test] Don't Close Server-Side Passive Socket Twice in `tcp-close`

src/rust/catmem/futures/pop.rs, src/rust/catmem/futures/push.rs, src/rust/catmem/mod.rs, src/rust/catmem/queue.rs
This PR closes https://github.com/demikernel/demikernel/issues/758
=> [catmem] Keep Track of Pending Operations

include/demi/types.h
- This PR closes https://github.com/microsoft/demikernel/issues/787
=> [bindings] Structures Are Not Packed

src/rust/demikernel/bindings.rs
- This commit closes https://github.com/microsoft/demikernel/issues/788
=> [bindings] Check for Invalid Storage Location

src/rust/catloop/duplex_pipe.rs, src/rust/catloop/futures/accept.rs, src/rust/catloop/futures/connect.rs, src/rust/catloop/mod.rs, src/rust/catloop/queue.rs, src/rust/scheduler/yielder.rs
This PR covers the following issues and enhancements:
1. Close #774 
2. Close #775 
3. Close #773
=> [catloop] Move to async functions and add yield and cancel on close

src/rust/catloop/futures/accept.rs, src/rust/catloop/futures/connect.rs, src/rust/catloop/mod.rs, src/rust/catmem/mod.rs, src/rust/demikernel/libos/memory.rs
This PR closes #776. I have also removed unnecessary borrow_mut and replaced with borrow
=> [catmem] Rename schedule function

.githooks/commit-msg, .github/workflows/devops.yml, linux.mk
Adding pre-commit hooks for checking commit messages.
=> [build] Pre-Commit Hooks

linux.mk, src/rust/pal/linux/shm.rs
This PR closes https://github.com/microsoft/demikernel/issues/318.
=> [catmem] Name Prefix Shared Memory Regions

src/rust/catmem/mod.rs, src/rust/catmem/pipe.rs
This PR partially addresses https://github.com/microsoft/demikernel/issues/701.
=> [catmem] States For Pipes

src/rust/catmem/mod.rs
=> [catmem] Add Drop Function

linux.mk
This PR fixes dependencies in the build system.
=> [build] Wrong Build Dependencies

src/rust/scheduler/scheduler.rs
Added tests for from_task_id() and remove() functionality. And some other minor improvements.
=> [scheduler] Improve tests

linux.mk
This PR increases build timeout.
=> [build] Increase Build Timeout

src/rust/catnip/runtime/memory/mempool.rs, src/rust/demikernel/libos/network.rs
This PR fixes some build warnings.
=> [build] Build Warnings

src/rust/catloop/mod.rs
This PR closes https://github.com/microsoft/demikernel/issues/808
=> [catloop] Inconsistent Port Allocation

src/rust/catloop/mod.rs, src/rust/inetstack/protocols/ip/ephemeral.rs, src/rust/inetstack/protocols/tcp/peer.rs, src/rust/inetstack/protocols/udp/peer.rs
This PR closes https://github.com/microsoft/demikernel/issues/807
=> [inetstack] Non Ephemeral Port May Get Released

tools/demikernel_ci.py
This PR closes https://github.com/microsoft/demikernel/issues/599
=> [ci] Enable tcp-echo  Catloop LibOS

src/rust/scheduler/scheduler.rs
This PR covers a series of commits for:
- Refactors to improve scope
- Refactors and renames to improve readability
- Simplification of test checks
=> [scheduler] Several scope, readability and test improvements

src/rust/catloop/mod.rs
This PR closes https://github.com/microsoft/demikernel/issues/670.
=> [catloop] Drop Trait Implementation

.gitignore, tools/ci/config/ci_map.yaml, tools/ci/src/base_test.py, tools/ci/src/ci_map.py, tools/ci/src/test_impls/pipe_open_test.py, tools/ci/src/test_impls/pipe_ping_pong.py, tools/ci/src/test_impls/pipe_push_pop.py, tools/ci/src/test_impls/tcp_close_test.py, tools/ci/src/test_impls/tcp_echo_test.py, tools/ci/src/test_impls/tcp_ping_pong_test.py, tools/ci/src/test_impls/tcp_push_pop_test.py, tools/ci/src/test_impls/tcp_wait_test.py, tools/ci/src/test_impls/udp_ping_pong_test.py, tools/ci/src/test_impls/udp_push_pop_test.py, tools/ci/src/test_instantiator.py, tools/ci/unit_tests/test_callback_example.py, tools/ci/unit_tests/test_ci_map.py, tools/ci/unit_tests/test_data/ci_map.yaml, tools/ci/unit_tests/test_data/scaffolding.yaml, tools/ci/unit_tests/test_test_impls.py, tools/ci/unit_tests/test_test_instantiator.py, tools/demikernel_ci.py, tools/demikernel_ci_new.py
This PR attempts to simplify the configuration and control over our CI infra. With this change, the libos->test->scenario->parameters mapping will be config. driven.
This PR only addresses system tests. Other areas of CI will be evaluated and address in separate PRs if needed.
Related issue: https://github.com/microsoft/demikernel/issues/804
=> [ci] Improve CI configurability

src/rust/scheduler/scheduler.rs
Simplified the `poll` function and deprecated the drop part.
=> [scheduler] Simplified the poll function and deprecated the drop part.

src/rust/catloop/duplex_pipe.rs, src/rust/catloop/futures/mod.rs, src/rust/catloop/mod.rs, src/rust/demikernel/libos/network.rs
This PR closes https://github.com/microsoft/demikernel/issues/812.
=> [catloop] Missing `async_close()`

.github/workflows/catcollar_new.yml, .github/workflows/catloop_new.yml, .github/workflows/catmem_new.yml, .github/workflows/catnap_new.yml, .github/workflows/catnapw_new.yml, .github/workflows/catnip_new.yml, .github/workflows/catpowder_new.yml
Created new workflow files that are dependent on existing workflows. We will run these along with the existing workflows until we are satisfied to move over to the new CI architecture.
=> [ci] New workflow files

examples/tcp-echo/server.rs
This PR closes https://github.com/microsoft/demikernel/issues/870.
=> [examples] Handle `ECANCELED`

src/rust/runtime/network/socket/state.rs
These contants are important when building on Windows.
=> [network] Use PAL constants in state

src/rust/catloop/mod.rs
This PR removes harvest on close.
=> [catloop] Remove Harvest on Close

src/rust/catnap/mod.rs
This PR moves Catnap towards our most recent architecture. It does the following: 
1. Removes moves to avoid implicit moves of variables on the synchronous path to another closure/async context.
2. Removes references to self in coroutines.
3. Explicitly passes all state into async coroutines, including the CatnapQueue, IoQueueTable (and eventually DemiRuntime)
=> [catnap] Move coroutines to standalone functions

src/rust/catnap/mod.rs, src/rust/catnap/queue.rs, src/rust/runtime/mod.rs, src/rust/runtime/queue/mod.rs
=> [runtime] Add IoQueueTable to DemiRuntime

src/rust/catnap/mod.rs, src/rust/runtime/mod.rs
This PR closes https://github.com/microsoft/demikernel/issues/903.
This PR closes https://github.com/microsoft/demikernel/issues/905.
=> [catnap] Don't Panic on Drop

src/rust/catloop/socket.rs
This PR closes https://github.com/microsoft/demikernel/issues/833.
=> [catloop] Interpose Error on Connect

src/rust/catnap/mod.rs, src/rust/catnap/queue.rs
=> [catnap] Check retry after try_push()

tests/rust/tcp-test/bind/mod.rs, tests/rust/tcp-test/main.rs, tools/demikernel_ci.py
- This PR closes https://github.com/microsoft/demikernel/issues/610
- This PR closes https://github.com/microsoft/demikernel/issues/821
- This PR closes https://github.com/microsoft/demikernel/issues/822
- This PR closes https://github.com/microsoft/demikernel/issues/823
- This PR closes https://github.com/microsoft/demikernel/issues/824
- This PR closes https://github.com/microsoft/demikernel/issues/825
- This PR closes https://github.com/microsoft/demikernel/issues/826
- This PR closes https://github.com/microsoft/demikernel/issues/827
- This PR closes https://github.com/microsoft/demikernel/issues/828
- This PR closes https://github.com/microsoft/demikernel/issues/830
- This PR closes https://github.com/microsoft/demikernel/issues/831
- This PR closes …
=> [test] Enable Integration Tests for Catloop

doc/testing.md
This PR updates the [doc/testing.md](https://github.com/microsoft/demikernel/blob/dev/doc/testing.md) file.
Commits:
- 33adaee96f92f73d9859bb8017ed1fd438865f3a - Updating the hyperlinks.
- 5e67430365964df09ef9f5d299c5c4c991440a0d - Updating the unit test script example.
- 04753211622439b5c6e4c8781581e3f891e9d9b8 - Updating the system-level script example.
=> [ci] Updating testing.md file.

src/rust/catloop/mod.rs
This PR closes #895.
Commits:
- 99c7132fe2483bcfbe3da2b865e3171bc3f2b93c - Inserting the profiler annotations.
- 1a237ee653ced5e4b75d48d45dae095450e0a7d2 - Fixing a typo.
=> [catloop] Performance counters

src/rust/catloop/mod.rs
This PR updates the names of push and pop coroutines.
=> [catloop] Updating task name

Cargo.toml, examples/rust/tcp-dump.rs, examples/rust/tcp-ping-pong.rs, examples/rust/tcp-pktgen.rs, examples/rust/tcp-push-pop.rs, examples/rust/udp-dump.rs, examples/rust/udp-echo.rs, examples/rust/udp-ping-pong.rs, examples/rust/udp-pktgen.rs, examples/rust/udp-push-pop.rs, examples/rust/udp-relay.rs, examples/tcp-close/client.rs, examples/tcp-close/server.rs, examples/tcp-echo/client.rs, examples/tcp-echo/main.rs, examples/tcp-echo/server.rs, examples/tcp-wait/client.rs, examples/tcp-wait/server.rs, src/rust/pal/constants.rs, tests/rust/tcp-test/accept/mod.rs, tests/rust/tcp-test/async_close/mod.rs, tests/rust/tcp-test/bind/mod.rs, tests/rust/tcp-test/close/mod.rs, tests/rust/tcp-test/connect/mod.rs, tests/rust/tcp-test/listen/mod.rs, tests/rust/tcp-test/socket/mod.rs, tests/rust/tcp-test/wait/mod.rs, tests/rust/tcp.rs, tests/rust/udp.rs
Bumping up the versions for the "windows" and "socket2" crates.
=> [demikernel] Bump up the windows and socket2 crates

src/rust/catloop/mod.rs, src/rust/catloop/queue.rs, src/rust/catloop/socket.rs, src/rust/catmem/mod.rs, src/rust/demikernel/libos/memory.rs, src/rust/demikernel/libos/mod.rs
This PR removes all Rc-RefCells from Catmem and moves to our SharedObject abstraction.
=> [catmem] Enhancement: Move to shared object

src/rust/catloop/socket.rs, src/rust/catmem/mod.rs, src/rust/catmem/queue.rs
This PR moves CatmemQueue to the shared object abstraction
=> [catmem] Enhancement: Move to shared object queues

src/rust/catloop/mod.rs, src/rust/catloop/queue.rs, src/rust/catloop/socket.rs
This PR moves CatloopQueue to the SharedObject abstraction
=> [catloop] Enhancement: Move to shared queues

src/rust/catloop/mod.rs, src/rust/catloop/socket.rs, src/rust/catmem/mod.rs
This PR removes standalone functions in Catmem.
=> [catmem] Enhancement: Remove standalone functions

src/rust/catloop/socket.rs, src/rust/runtime/network/ring/state.rs
This PR closes https://github.com/microsoft/demikernel/issues/916.
=> [catloop] Error When Ring Closing/Closed

src/rust/catcollar/mod.rs, src/rust/catnap/queue.rs, src/rust/catnap/socket.rs, src/rust/collections/concurrent_ring.rs, src/rust/runtime/mod.rs
This PR closes https://github.com/microsoft/demikernel/issues/954.
=> [runtime] Unify Retry Test

src/rust/inetstack/protocols/tcp/passive_open.rs, src/rust/inetstack/protocols/tcp/peer.rs
This PR closes https://github.com/microsoft/demikernel/issues/215.
=> [inetstack] Refuse Connections

src/rust/catloop/socket.rs, src/rust/catmem/queue.rs, src/rust/catmem/ring.rs, src/rust/collections/concurrent_ring.rs
This PR moves Catmem to use the concurrent ring buffer.
=> [catmem] Use concurrent ring buffer

src/rust/inetstack/protocols/tcp/peer.rs
This PR closes https://github.com/microsoft/demikernel/issues/220.
Instead of panicking, if ARP query fails, we fail gracefully.
=> [inetstack] Don't Panic if ARP Query Fail

tools/ci/config/ci_map.yaml
This PR enables TCP wait tests for Catloop.
=> [test] TCP Wait Tests for Catloop

src/rust/inetstack/protocols/tcp/peer.rs, tests/rust/tcp.rs
Add missing checks for wildcard and port number for the inetstack.
- https://github.com/microsoft/demikernel/issues/189
- https://github.com/microsoft/demikernel/issues/582
=> [inetstack] Add Checks for Bind

src/rust/inetstack/protocols/tcp/peer.rs
This PR partially addresses https://github.com/microsoft/demikernel/issues/235.
=> [inetstack] SeqNum and AckNum for RST Segments

src/rust/scheduler/page/page.rs, src/rust/scheduler/pin_slab.rs, src/rust/scheduler/scheduler.rs
We no longer drop running coroutines through the task handle but always explicitly remove them from the scheduler instead. This PR closes #723 and #884
=> [runtime] Remove drop bits from scheduler

src/rust/collections/async_queue.rs
It is not necessary to use a linked list for this data structure either.
=> [collections] Enhancement: Remove unnecessary linked list

src/rust/runtime/mod.rs, src/rust/runtime/network/socket/mod.rs
This PR simply adds more tracing around the new functions introduced to the SharedDemiRuntime
=> [runtime] Enhancement: add more tracing

.github/workflows/catnapw.yml
This PR re-enables Catnap CI on Windows.
=> [ci] Reenable Catnap CI on Windows

.github/workflows/catnip.yml, .github/workflows/catpowder.yml
This PR enables debug runs for Catnip and Catpowder libOSes.
=> [ci] Enabling Debug Runs for Catnip and Catpowder

.github/workflows/catnapw.yml
In this PR I updated CI scripts to run workflows on the head branch for Catnap on Windows.
=> [ci] Run Catnap CI on Windows on Head Branches of PRs

src/rust/inetstack/protocols/tcp/established/ctrlblk.rs, src/rust/inetstack/protocols/tcp/established/mod.rs, src/rust/inetstack/protocols/tcp/peer.rs, src/rust/inetstack/protocols/tcp/queue.rs
=> [inetstack] Finish implementing async tcp close

.github/workflows/catcollar.yml, .github/workflows/catloop.yml, .github/workflows/catmem.yml, .github/workflows/catnap.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml, src/rust/perftools/profiler/mod.rs, tools/demikernel_ci.py
In this PR I introduce required changes to gather performance statistics from CI runs on release mode, and upload results to Azure Storage.
**This should be considered an initial implementation**. Next, I intend to integrate performance regression on our pipeline.
=> [ci] Gather and Upload Performance Statistics

src/rust/inetstack/protocols/icmpv4/datagram/mod.rs, src/rust/inetstack/protocols/udp/datagram/mod.rs
This PR fixes build warnings on unused constants.
=> [build] Fix Build Warnings

src/rust/catcollar/mod.rs, src/rust/catloop/mod.rs, src/rust/catloop/queue.rs, src/rust/catloop/socket.rs, src/rust/catnap/mod.rs, src/rust/demikernel/libos/mod.rs, src/rust/demikernel/libos/network.rs, tests/rust/tcp-test/wait/mod.rs
This PR removes the synchronous close path from catnap,catcollar,catloop liboses.
=> [demikernel] Remove synchronous close() from catnap,catcollar,catloop liboses

tools/demikernel_ci.py
This PR closes https://github.com/microsoft/demikernel/issues/1061
=> [testing] More setup/clean up in the CI scripts

src/rust/catloop/socket.rs, src/rust/catmem/mod.rs, src/rust/catmem/queue.rs, src/rust/demikernel/libos/memory.rs
This pr moves the pending_ops & pack_result to runtime.
=> [catmem] Move pending_ops & pack_result to runtime

src/rust/catcollar/mod.rs
Enable tracking of pending_ops in catcollar. This is already done for other liboses, so just onboarding catcollar is straighforward. Cleanup (cancellation of pending_ops) happens in pack_result automatically.
=> [catcollar] Enable tracking of pending_ops

.github/workflows/catnip.yml, .github/workflows/catpowder.yml, tools/demikernel_ci.py
This PR partially addresses https://github.com/microsoft/demikernel/issues/1071 and https://github.com/microsoft/demikernel/issues/1072.
=> [test] Enabling Most System Tests in Debug Mode

src/rust/inetstack/protocols/tcp/passive_open.rs, src/rust/inetstack/protocols/tcp/peer.rs, src/rust/inetstack/protocols/tcp/queue.rs, src/rust/inetstack/protocols/tcp/tests/setup.rs
This PR closes https://github.com/microsoft/demikernel/issues/235.
=> [inetstack] Handle Reset Generation Correctly

nettest/src/grammar.y, nettest/src/tokens.l, src/rust/inetstack/protocols/tcp/tests/simulator.rs
This PR adds supports for RST packets in the network simulator engine.
=> [test] Support Reset Packages

linux.mk, windows.mk
This PR closes https://github.com/microsoft/demikernel/issues/1077
=> [test] Modular Unit Tests

src/rust/collections/pin_slab.rs, src/rust/runtime/scheduler/scheduler.rs
This code is no-op, so removing it.
=> [scheduler] Remove unnecessary code

nettest/input/push-retransmission.pkt, src/rust/inetstack/protocols/tcp/established/sender.rs
This PR closes https://github.com/microsoft/demikernel/issues/1094.
=> [inetstack] Set `PSH` Bit on Segment Retransmission

src/rust/catcollar/mod.rs, src/rust/catloop/mod.rs, src/rust/catloop/queue.rs, src/rust/catloop/socket.rs, src/rust/catmem/mod.rs, src/rust/catmem/queue.rs, src/rust/catnap/linux/transport.rs, src/rust/catnap/win/overlapped.rs, src/rust/catnip/mod.rs, src/rust/catpowder/mod.rs, src/rust/collections/async_queue.rs, src/rust/collections/async_value.rs, src/rust/demikernel/libos/memory.rs, src/rust/demikernel/libos/mod.rs, src/rust/demikernel/libos/network/libos.rs, src/rust/demikernel/libos/network/mod.rs, src/rust/demikernel/libos/network/queue.rs, src/rust/inetstack/mod.rs, src/rust/inetstack/protocols/tcp/established/mod.rs, src/rust/inetstack/protocols/tcp/passive_open.rs, src/rust/inetstack/protocols/tcp/peer.rs, src/rust/inetstack/protocols/tcp/queue.rs, src/rust/inetstack/protocols/tcp/tests/setup.rs, src/rust/inetstack/protocols/tcp/tests/simulator.rs, src/rust/inetstack/protocols/udp/peer.rs, src/rust/runtime/mod.rs, src/rust/runtime/scheduler/handle.rs, src/rust/runtime/scheduler/mod.rs, src/rust/runtime/scheduler/scheduler.rs, src/rust/runtime/watched.rs
This PR removes the TaskHandle from the codebase.
=> [demikernel] Remove TaskHandle (and other simplifications)

src/rust/inetstack/protocols/tcp/tests/simulator.rs
This PR adds the following improvements on our network simulator:
- Check for un-processed frames in the end of the simulation.
- Assert payload length for data segments.
=> [test] Improvements on Network Simulator

src/rust/inetstack/protocols/udp/peer.rs
This PR closes https://github.com/microsoft/demikernel/issues/260.
=> [inetstack] Clarifications of Port Scan Attack

nettest/input/local-close.pkt, nettest/input/remote-close.pkt, src/rust/inetstack/protocols/tcp/tests/simulator.rs
- This PR adds required support on the network simulator for close system calls
- This PR adds local and remote test cases to our testing suite.
- This PR exposes https://github.com/microsoft/demikernel/issues/1120
=> [test] Adding Local and Remote Close Test Cases

tools/demikernel_ci.py
This PR fixes the following issues on `demikernel_ci`:
- Standard error redirect.
- Single-thread run for unit tests.
=> [ci] Fixes on Demikernel CI

src/rust/inetstack/protocols/tcp/active_open.rs, src/rust/inetstack/protocols/tcp/established/ctrlblk.rs, src/rust/inetstack/protocols/tcp/established/mod.rs, src/rust/inetstack/protocols/tcp/passive_open.rs, src/rust/inetstack/protocols/tcp/socket.rs, tests/rust/tcp.rs, tools/ci/config/ci_map.yaml
=> [inetstack] Close for Passive Sockets

.github/workflows/catloop.yml, .github/workflows/catmem.yml, .github/workflows/catnap.yml, .github/workflows/catnapw.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml
This PR upgrades third-party actions in our CI.
=> [ci] Upgrading Github Actions

Cargo.toml, examples/tcp-echo/client.rs
This PR adds P50 and P99 statistics for TCP Echo.
=> [examples] Improving Statistics for TCP Echo

src/rust/runtime/scheduler/scheduler.rs
Breaking out the bug fix from PR #1181
=> [runtime] Bug Fix: Update current task id

src/rust/runtime/mod.rs
This PR adds some small microbenchmarks to our runtime.
=> [runtime] Enhancement: Adding microbenchmarks

linux.mk, src/rust/demikernel/libos/mod.rs, src/rust/demikernel/libos/network/mod.rs, src/rust/lib.rs, src/rust/pal/mod.rs, src/rust/runtime/mod.rs, tests/rust/common/mod.rs, tests/rust/tcp.rs, tests/rust/udp.rs
This PR updates `SharedNetworkLibOS` import in `NetworkLibOS`.
=> [libos] Enhancement: Update imports in NetworkLibOS

src/rust/lib.rs, src/rust/perftools/profiler/mod.rs, src/rust/perftools/profiler/scope.rs, src/rust/perftools/profiler/tests.rs
This PR moves scope related structures to a separate file and adds a small unit test for the async profiler.
=> [perf] Move some things into files and add a test

tools/ci/task/linux.py
This PR correctly enables the profiler on our CI infrastructure.
=> [ci] Enable Profiler on Run Task

tools/benchmark.py, tools/ci/job/utils.py, tools/demikernel_ci.py
This PR fixes connection to Azure Tables.
=> [ci] Connection to Azure Tables

.github/workflows/catloop.yml, .github/workflows/catmem.yml, .github/workflows/catnap.yml, .github/workflows/catnapw.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml
This PR enables CI on special branches.
=> [ci]  Enable CI On Special Branches

src/rust/catmem/mod.rs, src/rust/catnap/win/overlapped.rs, src/rust/demikernel/libos/network/libos.rs, src/rust/inetstack/protocols/tcp/established/background/mod.rs, src/rust/lib.rs, src/rust/perftools/profiler/mod.rs, src/rust/perftools/profiler/scope.rs, src/rust/perftools/profiler/tests.rs, src/rust/runtime/mod.rs
This PR adds support in our profiler for arbitrary async blocks, not just coroutines.
=> [perf] Add support for async blocks

.github/workflows/catloop.yml, .github/workflows/catmem.yml, .github/workflows/catnap.yml, .github/workflows/catnapw.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml, tools/benchmark.py, tools/ci/job/utils.py, tools/demikernel_ci.py, tools/perf.py
This PR adds initial support for performance reporting in PRs.
=> [ci] Performance Reporting

.github/workflows/catnap.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml, tools/benchmark.py, tools/ci/git.py, tools/perf.py
This PR introduces some cleanup on the CI infrastructure.
=> [ci] Clean Up

tools/ci/config/ci_map.yaml, tools/ci/job/factory.py, tools/ci/job/generic.py, tools/ci/job/linux.py, tools/ci/job/utils.py, tools/ci/job/windows.py, tools/demikernel_ci.py
=> [ci] Merge Windows and Linux Pipelines

Cargo.toml, src/rust/catnap/win/error.rs
This PR updates the following dependencies:
- `windows`
=> [contrib] Updating windows Crate

tools/ci/job/factory.py, tools/ci/job/linux.py
This PR fixes race condition on integration tests for TCP in Catloop LibOs
=> [ci] Race Condition on TCP Integration tests

src/rust/catnip/runtime/memory/manager.rs
This PR is follows up https://github.com/microsoft/demikernel/pull/1221.
=> [catnip] Disallow Zero-Length Buffer Allocation

tools/ci/job/factory.py, tools/ci/job/generic.py, tools/ci/job/linux.py, tools/ci/job/windows.py, tools/demikernel_ci.py
This PR enables unit tests runs on Windows in our CI.
=> [ci] Unit Tests for Windows

tools/ci/job/utils.py, tools/perf.py
This PR updates the CI to report performance on the NetworkLibOS scope.
=> [ci] Report Perfance on NetworkLibOS

src/rust/catnap/win/overlapped.rs, src/rust/inetstack/test_helpers/engine.rs, src/rust/runtime/mod.rs, tests/rust/common/libos.rs, tests/rust/udp.rs
This PR changes the timer resolution/number of iterations to run the scheduler before checking the clock depending on the remaining time out left.
=> [runtime] Enhancement: Refine timer resolution

tools/ci/git.py
This PR fixes the CI to get the right root commit of demikernel repository.
=> [ci] Get Root of Demikernel Repo

src/rust/demikernel/bindings.rs
This PR moves Demikernel to thread local storage.
=> [pdpix] Demikernel in Thread Local Storage

Cargo.toml, dpdk-rs/Cargo.toml
This PR updates the following third-party crates:
- `windows`
- `cc`
=> [contrib] Updating Third-Party Crates

CONTRIBUTING.md
=> [doc] CONTRIBUTING.md: `master` -> `main`

linux.mk
This PR closes https://github.com/microsoft/demikernel/issues/1240
=> [build] Copy All Libs On Install

.github/workflows/catnap.yml, shim/src/Makefile, tools/ci/job/factory.py, tools/ci/job/generic.py, tools/ci/job/linux.py, tools/ci/job/utils.py, tools/ci/task/linux.py, tools/demikernel_ci.py
This PR closes https://github.com/microsoft/demikernel/issues/1242.
=> [ci] Integrate Redis to CI Infrastructure

src/rust/inetstack/protocols/tcp/active_open.rs, src/rust/inetstack/protocols/tcp/constants.rs, src/rust/runtime/network/consts.rs
=> [inetstack] Bug Fix: Clamp window scale to 14

.github/workflows/catloop.yml, .github/workflows/catmem.yml, .github/workflows/catnap.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml, tools/ci/job/factory.py, tools/ci/job/windows.py, tools/demikernel_ci.py
This PR introduces Window support for integration tests on our CI infrastructure.
=> [ci] Support Integration Tests for Windows

tools/ci/config/test/catnapw.yaml, tools/ci/job/factory.py, tools/ci/job/windows.py, tools/demikernel_ci.py
This PR introduces support for System Tests in Windows for our CI infrastructure.
=> [ci] Support System Tests in Windows

.github/workflows/catnapw.yml
This PR enables unit tests for Windows in our CI.
=> [ci] Enable Unit Tests for Windows

shim/src/interpose.c
=> [shim] Correctly Interpose `fcntl()`

doc/setup.md
Just a few small updates to the setup notes since I went through this again with the new engineering VMs.
=> [docs] Update Setup Notes

src/rust/catnap/linux/transport.rs
This PR fixes https://github.com/microsoft/demikernel/issues/1263
=> [catnap] Don't Fail Silently When Cannot Set Socket Options

nettest/input/close/close-local.pkt, nettest/input/close/close-simultaneous.pkt
This PR adds a simultaneous close test case to our suite.
=> [test] Simultaneous Close

Cargo.toml, dpdk-rs/Cargo.toml, nettest/Cargo.toml
This PR updates the following third-party dependencies:
- `anyhow`
- `histogram`
- `cc`
- `cfgrammar`
- `libc`
=> [contrib] Updating Third-Party Dependencies

windows.mk
- This PR enables rust long on debug builds in Windows.
- This PR closes https://github.com/microsoft/demikernel/issues/403
=> [build] Turn on Rust Log on Windows

shim/src/ctrl/getsockopt.c, shim/src/ctrl/setsockopt.c
- This PR closes https://github.com/microsoft/demikernel/issues/1272
- This PR closes https://github.com/microsoft/demikernel/issues/1273
=> [shim] Interpose `getsockopt()` and `setsockopt()`

src/rust/catnap/win/transport.rs
This PR closes https://github.com/microsoft/demikernel/issues/1277
=> [catnapw] Enforce Close on ENOTCONN

.github/workflows/catnapw.yml, tests/rust/tcp-test/bind/mod.rs, tests/rust/tcp-test/main.rs
This PR closes https://github.com/microsoft/demikernel/issues/1030.
=> [test] Integration Tests Windows

linux.mk, src/rust/runtime/types/memory.rs, tests/c/linux.mk, tests/c/sizes.c, tests/c/windows.mk, windows.mk
- This PR closes https://github.com/microsoft/demikernel/issues/1280
- This PR closes https://github.com/microsoft/demikernel/issues/1279
=> [test] Test Sizes of C API

scripts/setup/config.ps1, scripts/setup/config.sh
This closes https://github.com/microsoft/demikernel/issues/1292.
=> [scripts] Script for Automating `config.yaml` Generation

.github/workflows/catloop.yml, .github/workflows/catmem.yml, .github/workflows/catnap.yml, .github/workflows/catnapw.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml, tools/benchmark.py, tools/ci/job/utils.py, tools/demikernel_ci.py, tools/perf.py
As a part of security focus, we are removing dependency on Azure Tables. Check for automated comments from Github Bot.
=> [ci] Report perf using Github artifacts only

src/rust/inetstack/protocols/tcp/active_open.rs, src/rust/inetstack/protocols/tcp/established/ctrlblk.rs, src/rust/inetstack/protocols/tcp/established/mod.rs, src/rust/inetstack/protocols/tcp/passive_open.rs, src/rust/inetstack/protocols/tcp/socket.rs, tests/rust/tcp.rs, tools/ci/config/test/catnip.yaml, tools/ci/config/test/catpowder.yaml
* This closes #1131 and #597 
* This closes the following test issues: close #606 and closes #607
=> [inetstack] Enhancement: Passive Close

src/rust/inetstack/protocols/tcp/passive_open.rs
=> [inetstack] Bug Fix: Correctly compute backlog

.github/workflows/catnap.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml, src/rust/catnap/linux/transport.rs, src/rust/catnap/win/overlapped.rs, src/rust/catnap/win/transport.rs, src/rust/demikernel/libos/network/libos.rs, src/rust/inetstack/mod.rs, src/rust/inetstack/protocols/arp/peer.rs, src/rust/inetstack/protocols/icmpv4/peer.rs, src/rust/inetstack/protocols/tcp/established/mod.rs, src/rust/inetstack/protocols/tcp/passive_open.rs, src/rust/perftools/profiler/mod.rs, src/rust/perftools/profiler/scope.rs, src/rust/runtime/mod.rs, tools/perf.py
Creates flamegraph and stack perf data for PRs.
Flamegraphs (in SVG format) will be stored in archives. Stack perf data will be archived as well as posted as comments on PRs.
=> [ci] Flamegraph and stack perf data

.github/workflows/catnap.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml
Fixing branch name for dev branch runs.
=> [ci] Fix branch name for dev branch runs

.github/workflows/catnap.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml
Guard against posting comments for dev branch.
=> [ci] Guard against posting comments for dev branch

.github/workflows/catnap.yml, .github/workflows/catnip.yml, .github/workflows/catpowder.yml, tools/perf.py
Changing the path for the FlameGraph repo to a better location in the filesystem.
=> [ci] Better path for FlameGraph repo

include/demi/cc.h, shim/include/glue.h, shim/src/epoll.h, shim/src/epoll/epoll.c, shim/src/epoll/epoll_ctl.c, shim/src/epoll/epoll_wait.c, shim/src/glue.c, shim/src/hashset.c, shim/src/hashtable.c, shim/src/interpose.c
Enhancement to the shim, where instead of looking at every element of the array for new events, we look only at added events.
=> [shim] Optimizing epoll_wait

examples/pipe-open/main.rs, examples/rust/pipe-ping-pong.rs, examples/rust/pipe-push-pop.rs, examples/rust/tcp-dump.rs, examples/rust/tcp-ping-pong.rs, examples/rust/tcp-pktgen.rs, examples/rust/tcp-push-pop.rs, examples/rust/udp-dump.rs, examples/rust/udp-echo.rs, examples/rust/udp-ping-pong.rs, examples/rust/udp-pktgen.rs, examples/rust/udp-push-pop.rs, examples/rust/udp-relay.rs, examples/tcp-close/main.rs, examples/tcp-echo/main.rs, examples/tcp-wait/main.rs
Adding timers for main() in all examples.
=> [examples] Measure end-to-end CPU cycles

src/rust/inetstack/protocols/peer.rs, src/rust/inetstack/protocols/tcp/tests/simulator.rs, src/rust/inetstack/protocols/udp/mod.rs
This PR introduces required to support to include an additional protocol in the network test simulator.
- Fixed various typos.
- Added some error log messages.
- Introduce protocol support in the simulator.
=> [nettest] Initial Support for an Additional Protocol

.github/workflows/catnip.yml, .github/workflows/catpowder.yml
With this, you will never have to manually run steps on VMs after they reboot! They would possibly have to be rebooted less often as well...
=> [ci] Automatically bootstrap VMs

src/rust/catnip/runtime/mod.rs, src/rust/inetstack/mod.rs
Add timers to recieve and transmit paths for catnip (includes inetstack receive/transmit).
=> [catnip] Add timers to recieve and transmit paths

linux.mk
This PR fixes our build system to clean up dangling artifacts.
=> [build] Clean Dangling SHIM Artifact

linux.mk, shim/Makefile
This PR updates the build system to build shim examples.
=> [build] Build SHIM Examples

shim/src/interpose.c
This PR fixes a race condition in the initialization of the SHIM library.
Before we were:
- Erroneous using atomic adds/subs for enclosing the critical session
- Not protecting initialization variables.
- Issuing memory barriers at wrong places.
=> [shim] Race Condition In Initialization

shim/src/queue.c
This PR isolates some changes introduced by https://github.com/microsoft/demikernel/pull/1351.
=> [shim] Use Direct Hash for FDs

shim/src/epoll.h, shim/src/interpose.c, shim/src/utils.h
This PR isolates some changes introduced by https://github.com/microsoft/demikernel/pull/1351.
=> [shim] Adding Condition Hints

src/rust/perftools/profiler/mod.rs, src/rust/perftools/profiler/scope.rs, tools/perf.py
Add num_calls to profiler output
=> [profiler] Add num_calls to profiler output

scripts/config/azure.yaml, scripts/setup/config.sh
This PR fixes typos in the config script.
=> [scripts] Typos in Config Script

tools/ci/job/linux.py, tools/ci/task/linux.py, tools/demikernel_ci.py
This PR introduces required changes to enable one to run Redis over catnip with `demikernel_ci.py`.
=> [ci] Support Running Redis with Catnip

.github/workflows/catnip.yml
This PR enables Redis in Catnip pipeline.
=> [ci] Run Redis in Catnip Pipeline

src/rust/runtime/memory/demibuffer.rs
This PR fixes a bug introduced in #1367. Now that we also allocate headroom for heap-allocated DemiBuffers, we can (and must) switch to using the same code for dereferencing both DPDK and heap-allocated buffers to account for the offset of the data in the buffer.
=> [runtime] Align DPDK and heap buffers for headroom
